### ISSUE TITLE
Mensajes de error aleatorios en jQuiz

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#100]
Crear una **función** que permita cambiar aleatoriamente [el mensaje de error que muestra jQuiz](https://github.com/profeIAP/retados/blob/f753de050b77b0523930d87b4aeeb9f5b1349721/js/quiz.js#L176) cuando el usuario se confunde al contestar.

La idea es "picar" al usuario (sin llegar a insultarlo) con mensajes "motivadores" del tipo:

- "Ni de lejos"
- "Vas a tener que afinar la puntería"
- "Prometo no contárselo a nadie"
- ...

No hace falta poner muchos mensajes, lo que realmente interesa es:
1. la función que genera los mensajes _aleatorios_
1. que podamos disfrutar con los mensajes

**Comment by profeIAP** [comment]
Rafael, has colocado código en el sitio equivocado y con errores de sintaxis (has olvidado algún ";")
Esto provoca que hayan dejado de funcionar los cuestionarios.
Aunque lo tengo corregido, al no afectar al resto de funcionalidad, no lo anotaré como "estropicio"

**Comment by profeIAP** [comment]
Rafael, no vuelvas a recuperar (y sin probar) un código que hace que los cuestionarios dejen de funcionar 😒

**Comment by Rafaelcraftero** [comment]
es que no puedo ver si funcionan o no

**Comment by Rafaelcraftero** [comment]
ya he arreglado lo de las ";" me faltaba una. Pero lo que no alcanzo a comprender es donde tiene que estar esta función ¿ Me podrías sugerir un sitio?

**Comment by profeIAP** [comment]
Hay un fallo (comentado sobre el propio commit) que provoca que sólo aparezca la primera RESPUESTA de cada PREGUNTA

**Comment by profeIAP** [comment]
Funciona perfectamente, enhorabuena Rafa.

No obtante, abro la tarea a la espera de una explicación (del comentario que te he incluido en el commit) pues se ha detectado en tu subida el motivo por el cual había dejado de funcionar jQuiz

**Comment by Rafaelcraftero** [comment]
creo q e he corregido el error y era que en cuestionario.json el index=0 y lo había cambiado pero eso me lo pusiste tú en clase cuando intentaba hacer lo de las etiquetas

**Comment by profeIAP** [comment]
Sospecho que no ha leído (o interpretado correctamente) mi comentario anterior.
Debido a las faltas de ortografía abro la tarea.

**Comment by Rafaelcraftero** [comment]
¿Qué faltas de ortografía? yo no veo ninguna.

**Comment by Rafaelcraftero** [comment]
vale ya se

**Comment by Rafaelcraftero** [comment]
No hay faltas en var respuestas. Lo acabo de mirar y encima por si acaso lo he mirado en un [corrector ortográfico](https://www.correctorortografico.com/)
