### ISSUE TITLE
Crear método Usuario::getID()

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#101]
Añadir a la clase _controller/Usuario.php_ el método indicado.

Para que funcione correctamente, deberás modificar [el constructor de la clase](https://github.com/profeIAP/retados/blob/f753de050b77b0523930d87b4aeeb9f5b1349721/controller/Usuario.php#L5) para que:
1. reciba dicha información
1. la anote como hace con el resto de atributos

**Comment by josufg** [comment]
@profeIAP Listo. La cierro.

**Comment by profeIAP** [comment]
Y a la primera... simplemente espectacular.
Gracias Josué
