### ISSUE TITLE
Modificar la invocación al constructor de Usuario.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#102]
Modificar [la creación del objeto Usuario en LoginClave::autenticar(...)](https://github.com/profeIAP/retados/blob/f753de050b77b0523930d87b4aeeb9f5b1349721/controller/LoginClave.php#L19) de modo que se proporcione el valor del campo USUARIO.ID

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Perfecto Carlos ¡Y a la primera! 👍
