### ISSUE TITLE
Añadir campo ID_USUARIO a view/pregunta.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#103]
Añadir [campo oculto a la edición de una PREGUNTA](https://github.com/profeIAP/retados/blob/f753de050b77b0523930d87b4aeeb9f5b1349721/view/pregunta.php#L27) que contenga el ID_USUARIO del creador de la PREGUNTA

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Perfecto Carlos salvo que debes cargar {{ID_USUARIO}} en lugar de {{ID}}

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Sigue igual, he usado tu versión (commit  4ece560) y sigue sin el ON DELETE CASCADE

**Comment by profeIAP** [comment]
Perfecta Carlos, me confundí de tarea.
Ésta, está bien.
Buen trabajo y disculpa el "despiste"
