### ISSUE TITLE
Eliminar mensaje publicar en redes sociales de jQuiz

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#105]
Eliminar el siguiente texto que aparece al terminar de contestar una encuesta.

![image](https://cloud.githubusercontent.com/assets/16881846/26007628/b5f6a952-3741-11e7-968a-d74e817aa2a5.png)

Deberás modificar js/quiz.js para resolverlo

**Comment by julioosos** [comment]
Terminada. El commit lo he subido por error asignado a la tarea #110, no lo tomes en cuenta.
Disculpa por las molestias

**Comment by profeIAP** [comment]
No te preocupes Julio, pasa en las mejores familias.
Ha quedado muy bien, gracias
