### ISSUE TITLE
Crear Pregunta::listar($idUsuario)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#106]
Crear el método indicado en _controller/Pregunta.php_ de modo que:

1. recupere todas las PREGUNTAS (tal y [como se hace actualmente](https://github.com/profeIAP/retados/blob/7698de5069f6d94173bc36d812306e1c3140cfdc/index.php#L192)) si no se indica un valor de $id_usuario
1. recupere sólo las entradas del usuario indicado por $id_usuario

**Comment by profeIAP** [comment]
Anoto comentarios sobre el propio commit

**Comment by profeIAP** [comment]
Cambio nombre de la tarea tras detectar "typo".

Se abre tras observar que no se ha implementado la funcionalidad indicada en la descripción de la tarea y comentada en clase.

**Comment by Rafaelcraftero** [comment]
he subido los cambios en el commit anterior con la tarea #86 asi que creo que ya esta terminadol

**Comment by profeIAP** [comment]
Desgraciadamente, esta tarea sigue sin funcionar, Rafael
