### ISSUE TITLE
Crear grupo /usuario/preguntas en index.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#107]
Deberá invocar al método Pregunta::listar(N) (creado en la tarea #106) siendo N el ID del usuario logado en el sistema actualmente.

Puedes obtener el ID del usuario pidiéndoselo a _Usuario::getID()_ implementado en la tarea #101

**Comment by josufg** [comment]
@profeIAP Listo.

**Comment by profeIAP** [comment]
Añado comentario al commit.

Prueba el código antes de subir la versión definitiva... nada mejor que utilizar la siguiente opción del menú

![image](https://cloud.githubusercontent.com/assets/16881846/26206698/d1d13612-3be5-11e7-95bd-2fe8c564f6b0.png)

**Comment by profeIAP** [comment]
Añado comentario

**Comment by josufg** [comment]
@profeIAP Listo pues

**Comment by profeIAP** [comment]
Pefecto Josu, ¡enhorabuena!
