### ISSUE TITLE
Activar opción Perfil del menú en preguntas.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#110]
Activar la opción de menú _Perfil_ cuando el usuario esté listando PREGUNTAS

![image](https://cloud.githubusercontent.com/assets/16881846/26009241/340ede3a-3748-11e7-8828-207eebdc4b52.png)

Deberás realizar una [implementación similar a ésta](https://github.com/profeIAP/retados/blob/7698de5069f6d94173bc36d812306e1c3140cfdc/view/inicio.php#L5) en view/preguntas.php

**Comment by manu21499** [comment]
@profeIAP Listoo 🥇

**Comment by profeIAP** [comment]
Qué desfachatez: te has puesto la medalla y todo.
¿Tan seguro estás de haberlo hecho bien? 😏

Yo lo veo muy "negro"

![image](https://cloud.githubusercontent.com/assets/16881846/26064275/bfbb0838-3990-11e7-9160-417f2f2b2cfb.png)

Pero, descuida, lo pondremos como otra tarea... ¡Buen trabajo! (y a la primera... ya te estás "acostumbrando" a ésto ¿no? 😉)
