### ISSUE TITLE
Evitar que el menú Perfil aparezca "ennegrecido"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#111]
Tras implementar la activación de la entrada Perfil del menú principal (tarea #110), el desplegable aparece en negro

![image](https://cloud.githubusercontent.com/assets/16881846/26064406/2703dd1c-3991-11e7-8639-3901c22460c9.png)

en lugar de su color habitual.

![image](https://cloud.githubusercontent.com/assets/16881846/26064444/3d01bf26-3991-11e7-9b1c-77dfdc9391d3.png)

Corregir la CSS para que no ocurra.

**Comment by Mahc99** [comment]
Pues terminada.

**Comment by profeIAP** [comment]
Pues ha quedado espectacular, gracias Migue

**Comment by profeIAP** [comment]
"Jugando" con la aplicación se observa que no funciona como se esperaba...

![image](https://cloud.githubusercontent.com/assets/16881846/26415326/69e52b9a-40b2-11e7-9027-946ab59cf276.png)

Observa qué ocurre si:
1. Haces "login" en el sistema
1. Seleccionas _Perfil/Mis preguntas_
1. Vuelves a pinchar en _Perfil_

**Comment by profeIAP** [comment]
Para reproducirlo hay que:
1. Seleccionar Mi Perfil > Mis preguntas
1. Volver a desplegar el menú y pasar por sus distintas entradas (Mis preguntas y Salir a día de hoy)

**Comment by profeIAP** [comment]
@JaviierM me asigno esta tarea puesto que es compleja y no vas a tener tiempo de poder resolverla.
Ya tendremos oportunidad de aprender a manejar hojas de estilo CSS
