### ISSUE TITLE
Crear método GET:/cuestionarios/fallar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#115]
Crear en _index.php_ el método indicado.

Su única responsabilidad será [anotar en el fichero de log](https://github.com/profeIAP/retados/blob/ed9e5de5bcf3080ab0e7f1af183416a894b3a74c/index.php#L150) el mensaje "El USUARIO ha fallado la PREGUNTA"

**Comment by josufg** [comment]
@profeIAP Listo

**Comment by profeIAP** [comment]
Fantástico Josu, buen trabajo
