### ISSUE TITLE
Anotar acierto y/o fallo de la RESPUESTA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#116]
Modificar _js/quiz.js_ de modo que:
1. invoque a _GET:/cuestionarios/acertar_ si la RESPUESTA del USUARIO **es** correcta
1. invoque a _GET:/cuestionarios/fallar_ si la RESPUESTA del USUARIO **no es** correcta

Es más que posible (y se asuma como "normal") que el CUESTIONARIO deje de funcionar y aparezca un mensaje de error en pantalla tras la invocación.

No será obligación tuya arreglarlo, sólo determinar cómo hacer que el CUESTIONARIO invoque a los métodos indicados en función de si acierta (o no) la PREGUNTA... ya arreglaremos el desaguisado 👍

**Comment by profeIAP** [comment]
Igual te resulta de utilidad [la siguiente documentación](https://www.w3schools.com/jquery/jquery_ajax_get_post.asp)

**Comment by flobato322** [comment]
Terminada creo:)

**Comment by profeIAP** [comment]
Ese "creo" no me gustó en clase y, tras observar que ha dejado de funcionar, mucho menos verlo aquí escrito 😏
Está casi perfecto pero sospecho que cuando me dijiste que lo habías probado (y que salían en el log los mensajes) me estabas "tangando" 😒
