### ISSUE TITLE
Crear método POST:/signup

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#117]
Crear el método indicado de forma que podamos dar respuesta al formulario _registro de usuario_ de la tarea #79.

Mostrará:
1. **GET:/** si coinciden las claves introducidas en el formulario de alta
2. **GET:/signup** (con [mensaje de error](https://github.com/profeIAP/retados/commit/9210af184f3b30d7f2b7e5defc7977b7ad0ea979#diff-828e0013b8f3bc1bb22b4f57172b019dR133), "Las contraseñas no coinciden") en caso contrario

**Comment by profeIAP** [comment]
"Descifrado" el motivo por el que no salía el mensaje de error.
Añado comentario a tu último commit.

**Comment by josufg** [comment]
@profeIAP Es verdad. No me había dado cuenta de eso.

**Comment by profeIAP** [comment]
Sigue sin salir el mensaje... no has corregido el comentario que te he indicado 😳

**Comment by profeIAP** [comment]
Genial Josué, como hablamos, aunque salga el mensaje de error donde no debe, tu trabajo está bien hecho.
Gracias
