### ISSUE TITLE
Crear método Usuario::guardar($usuario)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#118]
Crear método que permita [almacenar en la BD](https://github.com/profeIAP/retados/blob/fd8e69b41b8d984eb47b00eb5b4cd9eedca74433/controller/Respuesta.php#L53) los datos de un nuevo USUARIO.

**Comment by profeIAP** [comment]
Se cambia la dificultad de la tarea tras delegar en otra la mayor parte de la responsabilidad

**Comment by manu21499** [comment]
@profeIAP Listo.

**Comment by profeIAP** [comment]
**¿?** Se observa que se ha modificado la forma de autenticar los usuarios y no existe el método Usuario::guardar($usuario)

1. ¿Hemos podido confundir la tarea a la hora de hacer el commit?
2. ¿Querías decir tarea #123 realmente?

**Comment by profeIAP** [comment]
Perfecto, buen trabajo Manu
