### ISSUE TITLE
Añadir campo USUARIO.NOMBRE_COMPLETO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#120]
Añadir el campo NOMBRE_COMPLETO a la tabla USUARIO para poder indicar el nombre y apellidos del USUARIO que se ha registrado en el sistema.

No debe olvidarse actualizar el fichero model/scripts/table_usuario.sql

**Comment by julioosos** [comment]
Terminada.

**Comment by profeIAP** [comment]
La BD "binaria" está perfecta; no lo estaba tanto el fichero sql que has actualizado.

Observa que la tabla USUARIO incluye un campo ROL que no aparece en la SQL.

Agradecería lo incluyeses:

`   "ROL"  TEXT CHECK( "ROL" IN ('Alumno','Profesor','Administrador') ) NOT NULL DEFAULT 'Alumno'
)`

**Comment by julioosos** [comment]
Terminada.

**Comment by profeIAP** [comment]
Se observa que has modificado (correctamente) el script pero la BD sigue sin coincidir con el script SQL

**Comment by julioosos** [comment]
Terminada

**Comment by profeIAP** [comment]
Perfecto Julio 👍
