### ISSUE TITLE
Crear método LoginClave::autenticarEmail($pdo, $email, $clave)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#121]
Crear el método indicado cuya implementación será idéntica a LoginClave::autenticar() salvo que se utilizará el email (en lugar del nombre de USUARIO) a la hora de realizar la comprobación.

Lo único que cambia es [la clausula _where_ en la siguiente línea](https://github.com/profeIAP/retados/blob/master/controller/LoginClave.php#L11)

**Comment by flobato322** [comment]
Terminada

**Comment by profeIAP** [comment]
Añado comentario al commit

**Comment by manu21499** [comment]
@profeIAP Terminada

**Comment by profeIAP** [comment]
Casi, te he añadido comentario al commit.

Te recomendaría asegurarte que puedes entrar en el sistema usando cualquiera de las combinaciones email/clave existentes en la BD antes de dar por finalizada la tarea.

**Comment by manu21499** [comment]
@profeIAP Terminada

**Comment by profeIAP** [comment]
Casiiii...

**Comment by manu21499** [comment]
@profeIAP Terminada

**Comment by profeIAP** [comment]
Incluyo comentario sobre el commit

**Comment by manu21499** [comment]
@profeIAP Terminada 👍

**Comment by profeIAP** [comment]
Ahora sí, buen trabajo Manuel
