### ISSUE TITLE
Delegar en LoginClave::autenticarEmail() la entrada en el sistema

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#123]
Cambiar [la siguiente línea](https://github.com/profeIAP/retados/blob/master/index.php#L238) para que se compruebe (utilizando LoginClave::autenticarEmail() implementado en la tarea #121) si el USUARIO puede (o no) entrar en el sistema

**Comment by profeIAP** [comment]
Esta tarea sigue sin estar implementada (como me dijiste que habías confudido los números de tarea, también he mirado en la otra que)

**Comment by manu21499** [comment]
@profeIAP Terminada 👍

**Comment by profeIAP** [comment]
Y bien terminada que está... genial
