### ISSUE TITLE
Buscar iconos para las ACCIONES más habituales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#125]
Se deberán encontrar imágenes (preferiblemente iconos lo más minimalistas posibles y que sean estéticamente parecidas entre si) para ilustrar las acciones que más se utilizarán:

+ Practicar
+ Retar
+ Crear pregunta
+ Mis preguntas
+ Mi perfil
+ ...

**Comment by j1m1** [comment]
¿Te los mando al correo a ver que te parecen?

**Comment by j1m1** [comment]
![retar](https://cloud.githubusercontent.com/assets/15939356/26301286/053f2484-3ee1-11e7-892c-87aaac967b68.png)
![practicar](https://cloud.githubusercontent.com/assets/15939356/26301292/0993b4d2-3ee1-11e7-8992-2e1e0843be9b.png)
![mis preguntas](https://cloud.githubusercontent.com/assets/15939356/26301296/0d0942e4-3ee1-11e7-8320-439278ce9fda.png)
![mi perfil](https://cloud.githubusercontent.com/assets/15939356/26301300/0fe74682-3ee1-11e7-982b-92728aace1f1.png)
![crear pregunta](https://cloud.githubusercontent.com/assets/15939356/26301302/12b57fd2-3ee1-11e7-8319-0e31cb9f2927.png)

**Comment by profeIAP** [comment]
A mi me gustan... ¿qué opináis los demás?

**Comment by profeIAP** [comment]
Jesús... sería de agradecer indicases las librerías de iconos de las que has obtenido las imágenes de arriba por si hubiese que ampliar en un futuro y/o hiciese falta acceder a ella por algún motivo en particular.

**Comment by j1m1** [comment]
Todos los iconos los he sacado de: freepik

**Comment by profeIAP** [comment]
Gracias por la referencia Jesús
¿Son iconos sueltos o pertenecen a algún tema y/o colección?

**Comment by j1m1** [comment]
Desgraciadamente, son iconos sueltos...

**Comment by profeIAP** [comment]
Sin problemas, si fuesen todas de un tema y/o colección y nos sirviesen (tal cual están) sería porque algún diseñador lo hubiese diseñado expresamente para nosotros 😉

Gracias Jesús, muy buen trabajo
