### ISSUE TITLE
Incluir las ACCIONES más habituales en jPortilio

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#126]
Incluir los textos e imágenes de las ACCIONES más habituales (ver tarea #125) en sustitución de la "frutería" actual

![image](https://cloud.githubusercontent.com/assets/16881846/26252314/34ccaaba-3cb0-11e7-98f3-3ee9964b1858.png)

**Comment by flobato322** [comment]
Terminada

**Comment by profeIAP** [comment]
Ok, esperamos el commit para poder "disfrutarlo" 😉

**Comment by profeIAP** [comment]
Ha quedado muy chulo Fran, enhorabuena.

Observa que quedan "bordes grises" debido a que no has eliminado completamente los espacios que ocupaban los iconos anteriores.

![image](https://cloud.githubusercontent.com/assets/16881846/26454512/9b6947cc-4167-11e7-8051-52160900afaf.png)

Agradecería lo corrigieses

**Comment by manu21499** [comment]
@profeIAP Me asigno la tarea

**Comment by profeIAP** [comment]
Y tienes mi consentimiento por incomparecencia de Fran el último día de clase.
Lástima que no la hayas podido finalizar
