### ISSUE TITLE
Crear trigger asigne ACCION.FECHA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#131]
Crear trigger que asigne la fecha actual al campo FECHA de la tabla ACCION cuando se inserte una nueva entrada.

Sirva [de referencia el ya implementado](https://github.com/profeIAP/retados/commit/25bcf97502e58622d6d7c220b683ac38c9776604) en la tarea #48

**Recuerda** actualizar la SQL _model/scripts/table_accion.sql para que incluya tanto la creación de la tabla como el trigger que has definido

**Comment by YellowZaki** [comment]
Creo que es mejor poner directamente la fecha de creación como valor por defecto de la columna FECHA:

CREATE TABLE accion (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_USUARIO" TEXT DEFAULT (0),
    **"FECHA" DATETIME DEFAULT CURRENT_TIMESTAMP,**
    "RUTA" TEXT
)

**Comment by profeIAP** [comment]
Una solución mucho más limpia y eficiente que la planteada originalmente.
Gracias y enhorabuena Alberto 👏👏👍
