### ISSUE TITLE
Cargar PREGUNTA para ser editada

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#14]
Crear [método en el controlador](https://github.com/profeIAP/retados/blob/436f210295d66cb79ceae3cc686155c3ed90eae0/index.php)  que, utilizando los accesos a datos implementados (tareas #4 y #13) prepare la información que mostrará la vista "Edición de Pregunta" (tarea #9)

**Comment by profeIAP** [comment]
Cambio el título de la tarea para facilitar su comprensión.

**Comment by profeIAP** [comment]
Carlos, ignora el comentario que te hice esta mañana: en lugar de unir en una única variable los datos de la pregunta y sus respuestas, opta por incluir la información en dos variables distintas (y que sea la vista quien se encargue de mostrarlas correctamente)

Asignaríamos las claves _pregunta_ y _respuestas_ en el array tal y [como hacíamos en el proyecto del curso pasado](https://github.com/profeIAP/panelDeControl/blob/080c970e52551315dbce1559ea94e4be1febfaba/index.php#L186) con la clave _alumnos_

Como imagino que te surgirán dudas, pregúntame en clase

**Comment by josufg** [comment]
@profeIAP No tengo ganas de cambiar más de tarea. Te he pedido cita previa para que me orientes acerca de esta tarea. Voy a darle caña ya

**Comment by profeIAP** [comment]
A la espera quedo...

**Comment by josufg** [comment]
@profeIAP Voy con la parte de respuesta. Voy a publicar también un par de noticias en el blog

**Comment by profeIAP** [comment]
Genial... deseando estoy de ver los cambios, Josué

**Comment by profeIAP** [comment]
Siento encargarme de implementar esta tarea pero se trata de una de las tareas "críticas" de este milestone y, sin ella, no podríamos darlo por finalizado.

Opto por cogerla tras no observar una evolución significativa en los 14 días que la has tenido asignada (sorry)

**Comment by profeIAP** [comment]
Al final resulta que ya la tenías implementada ¿?
¿Por qué no la cerraste Josué? 
Quito la "basurilla" innecesaria y te devuelvo la "autoría" de la misma.
