### ISSUE TITLE
Crear métodos Cuestionario::acertar($idPregunta) y Cuestionario::fallar($idPregunta)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#140]
Añadir los métodos indicados a la clase CUESTIONARIO con el [código existente actualmente en index.php](https://github.com/profeIAP/retados/blob/73a40b76a1012adb3529dd8a374dfbf737dd8739/index.php#L282)

**Comment by josufg** [comment]
@profeIAP Listo

**Comment by profeIAP** [comment]
Perfecto, Josu
