### ISSUE TITLE
Mostrar el mensajes de error correctamente en signup.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#144]
Maquetar correctamente la vista de registro de usuarios para que los mensajes de error aparezcan correctamente (entre el logotipo del proyecto y el formulario donde se introducen los datos)

![image](https://cloud.githubusercontent.com/assets/16881846/26496861/733783a0-4229-11e7-9ef7-b408b628309e.png)

**Comment by josufg** [comment]
@profeIAP Listo

**Comment by profeIAP** [comment]
"Perfect bonus"... buen trabajo Josu
