### ISSUE TITLE
Refactorizar GET:/cuestionarios/generar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#146]
Mover [el código actualmente existente](https://github.com/profeIAP/retados/blob/master/index.php#L270) en index.php [al método Cuestionario::generar()](https://github.com/profeIAP/retados/blob/master/controller/Cuestionario.php#L5) de modo que GET:/cuestionarios/generar contenga única y exclusivamente [una llamada a Cuestionario::generar(2)](https://github.com/profeIAP/retados/blob/master/index.php#L280)

**Comment by josufg** [comment]
@profeIAP Se me olvido el commit pero ya esta listo

**Comment by profeIAP** [comment]
Anoto sobre el propio commit

**Comment by josufg** [comment]
@profeIAP Recorcholis y repampanos. Siempre faltan cosas jajaja
