### ISSUE TITLE
Crear método Pregunta::guardarRepuestas()

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#15]
Crear método que recoja los datos de las RESPUESTAS introducidos en la vista "Edición de Pregunta" (tarea #9) e invoque, individualmente para cada respuesta, al método Respuesta::guardar() definido en la tarea #11

**Comment by carlosaj98** [comment]
Ya la he terminado. PD: en el commit salgo como usuario pero soy yo :)

**Comment by profeIAP** [comment]
Está casi perfecto Carlos salvo que has confundido el orden de los parámetros en el _forEach_
Corrígelo, please

**Comment by carlosaj98** [comment]
Creo que ya

**Comment by profeIAP** [comment]
Ahora sí, perfecto Carlos.
¡Gracias!
