### ISSUE TITLE
Cambiar plantilla usada en la web

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#19]
Cambiar el _layout.php_ para que haga uso de [la siguiente plantilla](http://www.bootply.com/render/100702)

Deberá garantizarse (como mínimo) la existencia de las etiquetas:

1. {% block cabecera %} para permitir la inclusión de nuevas hojas de estilo y/o librerías javascript
1.  {% block cuerpo %} para habilitar la inclusión de los distintos formularios y listados de nuestra aplicación

**Comment by profeIAP** [comment]
Tiene muy buena pinta Alberto y lo has hecho en tiempo "record", enhorabuena-

No obstante se agradecería:
1. Incluyas las imágenes en el directorio $WEB/img (para que los iconos y botones aparezcan correctamente) 
1. Quites todos los contenidos de relleno (salvo el pie) pues no aporta información y mete ruído (no temas, ya está en GitHub, podremos recuperarlo en cualquier momento) 
![captura de pantalla de 2017-03-13 17-25-14](https://cloud.githubusercontent.com/assets/16881846/23864267/447cdab6-0812-11e7-8719-e2d0d369fd54.jpg)
1. Observa que las rutas a las hojas de estilo y ficheros js deben empezar por /css y /js respectivamente (si no pones la barra inicial fallarán como le está pasando a @Patriexd con su formulario)
1. Al hacer click sobre {RetA2} no está conduciendo a '/' (te lleva a la url que tengas con un # al final, por lo que se queda donde está)

**Comment by YellowZaki** [comment]
1. El directorio /assets no viene incluido en la plantilla por lo que algunas imágenes no cargan.
https://s22.postimg.org/nmue0btzl/Captura_de_pantalla_de_2017_03_16_13_26_04.png
En un futuro si hacen falta esas imágenes puedo poner otras que la sustituyan.

2. Para no perder la estructura de la página web he sustituido el relleno por otro relleno más relacionado con el tema. No creo que moleste ahora mismo.

3. Arreglado

4. Arreglado

5. He añadido la hoja de estilos bootstrap.css a layout.php. No sé si está bien.

**Comment by profeIAP** [comment]
Esperaré a que subas correctamente la plantilla para corregir y dar por buena (si procede) la solución.

De momento, vete preparando para la que te puede caer 

![image](https://cloud.githubusercontent.com/assets/16881846/24006693/d67d5682-0a6c-11e7-9deb-9f11c88d2b5e.png)

**Comment by YellowZaki** [comment]
Corregida!

**Comment by profeIAP** [comment]
Tiene muy buena pinta, pero sigo sin ver los iconos ¿?
![](https://cloud.githubusercontent.com/assets/16881846/23869143/478cb89c-0822-11e7-812b-f70fcbab38dc.jpg)

**Comment by YellowZaki** [comment]
Vale, resulta que no son imágenes, sino iconos de bootstrap. Estos iconos usan una fuente que no estaba en los directorios y ya las he incluido por lo que debería funcionar.

**Comment by profeIAP** [comment]
Simplemente espectacular... me alegra que hayas aprendido (y comprendido, que no es poco) la existencia (y uso) de ese tipo de letras. Enhorabuena Alberto, gran trabajo y gran progreso.

No obstante, sigo observando que se ha "escapado" un formulario en el pié de todas las vistas de nuestra web (por lo que debe estar en view/layout.php)

![captura de pantalla de 2017-03-20 17-09-02](https://cloud.githubusercontent.com/assets/16881846/24109213/3de28b64-0d90-11e7-93d3-39d94f9ef8ec.png)

Todos los puntos anteriores (incluido los mensajes de error) parecen estar perfectos ¡Genial! Gracias

**Comment by YellowZaki** [comment]
Listo

**Comment by profeIAP** [comment]
Genial, ahora sí.
¡Ha quedado fantástico!
Gracias Alberto, gran trabajo.
