### ISSUE TITLE
Incluir editor WYSIWYG en la edición de PREGUNTA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#20]
Incluir el editor TinyMCE al textarea que permite insertar el texto de la pregunta en el formulario de edición de PREGUNTA de la tarea #9.

Se etiqueta como dificultad _normal_ [por haber sido implementado el curso pasado](https://github.com/profeIAP/panelDeControl/commit/aaca846e983f1888a716f19ac7f81cf6b80e27de#diff-0f2508d8f1191fac02fd6df909c8fbd6R48) en el panelDeControl y contar con una solución de referencia.

**Comment by profeIAP** [comment]
Francamente espectacular, muy buen trabajo, Alberto.
¡Gracias!

![image](https://cloud.githubusercontent.com/assets/16881846/24047871/5539be42-0b27-11e7-890e-1a63a21d7b3a.png)

**Comment by profeIAP** [comment]
Tras buscar el ~ir~responsable de crear la carpeta _/tinymce_ encuentro que se te escapó el detalle al incluir el editro WYSIWYG en el proyecto.

Como tienes capacidad de sobra, abro la tarea a la espera de que corrijas el "despiste" 😏

**Comment by YellowZaki** [comment]
No lo entiendo, el editor wysiwyg es tinymce y está en esa carpeta.

**Comment by profeIAP** [comment]
Pero se pueden cambiar los archivos para ubicarlos en las carpetas "apropiadas" ¿no te parece? ¬¬

**Comment by YellowZaki** [comment]
Listo https://github.com/profeIAP/retados/commit/c14d748c1f019e1f9fc613dd8d44ddd8203a2c53

**Comment by profeIAP** [comment]
Observo que has cambiado correctamente los ficheros de ubicación pero has olvidado utilizar `git rm` para que deje de aparecer la carpeta tinymce en el directorio raíz del proyecto 😜

**Comment by profeIAP** [comment]
Perfecto Alberto, gran trabajo.
Gracias
