### ISSUE TITLE
Añadir filtro por texto de la PREGUNTA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#21]
Añadir método GET:preguntas/buscar/porTexto similar al [implementado el curso pasado](https://github.com/profeIAP/panelDeControl/blob/72b5117f5dcd0f6cb3934d2c637199ae991c1d6f/index.php#L315) para poder filtrar las preguntas (por el texto de la pregunta) igual que filtrábamos los partes por el alumno al que habían sido puestos.

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Carlos, la idea era adaptar la búsqueda (que implementamos el curso pasado) al nuevo contexto: búsqueda de preguntas cuyo texto incluya la cadena introducida por el usuario.

Espero haber sabido explicarme :)

**Comment by profeIAP** [comment]
Cambio la etiqueta pues requerirá adaptar el código actualmente existente a la librería controller/AccesoDatos

**Comment by profeIAP** [comment]
Juan Carlos, dejo por escrito lo que te he comentado al salir hoy de clase: no asumiré esta tarea por estar próxima a su finalización por tu parte.

Desde aquí anirmarte a cerrarla lo antes posibles para no sufrir las consecuencias de ser "abducida" por el profesor 😏

**Comment by profeIAP** [comment]
Casi perfecto, sólo falta el último detalle.

Te [dejo comentario](https://github.com/profeIAP/retados/commit/0226d11efb0b330abffaeb9af1330a2a80da4170#commitcomment-21880380) en el punto que falta para dar por finalizada la tarea.

**Comment by profeIAP** [comment]
Genial, gracias Juan Carlos, gran trabajo 👍
