### ISSUE TITLE
Buscar plugin para etiquetar PREGUNTAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#24]
Buscar e incluir en el proyecto librería javaScript que permita añadir etiquetas (con sugerencias conforme se va escribiendo) a las PREGUNTAS que se vayan creando.

Se etiqueta como reto al requerir bastante tiempo de pruebas.

Sirvan como referencia las siguientes librerías:

1. Bootstrap [TagsInput](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)
1. jQuery [TagEditor](https://goodies.pixabay.com/jquery/tag-editor/demo.html)
1. jQuery [Tags Manager](https://maxfavilli.com/jquery-tag-manager)

**Comment by profeIAP** [comment]
D. Rafael, observo que ha incluido una nueva carpeta (_/tinymce/js/..._) al proyecto pero no veo que se haya incluido dicho plugin a la caja de texto que mencionamos en clase para poder probarlo (idealmente en el formulario _view/pregunta.php_ de @Patriexd )

Agradeceríamos: 
1. nos "ilustrase" (y asombrase) con la nueva funcionalidad que permite etiquetar
1. mueva la carpeta _/tinymce_ a la carpeta donde estamos incluyendos todas las librerías javascript (__/js_)

**Comment by profeIAP** [comment]
Observo que [ha incluido un listado de asignaturas ](https://github.com/profeIAP/retados/commit/382c7412e4bdddbf99d79ab4bcf4a787882dee22#diff-938a889300a6ef0a8681e3bc6f552a9a) pero ninguna parece funcionar al introducirlas en la caja de texto.

Igualmente, se observa que **TODAS** las cajas (incluidas las de las respuestas que tenía @Patriexd) han visto menguado su tamaño.

**Comment by profeIAP** [comment]
Perdóneme que insista pero, ya en el commit 472bc73 se observa que las cajas tenían una altura superior a la que ud. ha establecido con sus últimos cambios.

Agradeceríamos restituyese el status anterior

![image](https://cloud.githubusercontent.com/assets/16881846/24762050/78f74a86-1aed-11e7-8a02-41ba170277a8.png)

**Comment by profeIAP** [comment]
Rebajo el nivel de dificultad tras incluir las dependencias e implementar una versión preliminar del etiquetado de preguntas en el formulario view/prueba.php.

**Comment by profeIAP** [comment]
Faltaría por implementar el uso del fichero json con las etiquetas predefinidas.

**Comment by profeIAP** [comment]
Esta tarea va a ser su perdición D. Rafael, le sugeriría abandonarla antes de que acabe con su persona.
No funciona el autocompletar 😳

**Comment by Rafaelcraftero** [comment]
Ya no es mi tarea es la #69

**Comment by profeIAP** [comment]
No le entiendo D. Rafael... la **tarea 69** no es suya y esta en la que estamos no termina de funcionar.
Si se refiere a que terminar lo que debería funcionar (el autocompletar) no es cosa suya, quisiera indicarle que debe estar confundido.

La tarea 69 tiene como cometido mostrar como etiquetas (que se pueden quitar y aparecen marcadas en azul) la lista de valores que existe en la BD para una pregunta completa.

**Comment by profeIAP** [comment]
Rafael, ha vuelto a cerrar esta tarea sin realizar ningún cambio ni observarse que funcione el autocompletado de etiquetas... vuelvo a abrirla

**Comment by profeIAP** [comment]
[jQuery Tags Manager](https://maxfavilli.com/jquery-tag-manager) funciona bastante mejor que la implementación de [Bootstrap TagsInput](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)
