### ISSUE TITLE
Evitar que aparezca el autor del GRUPO en MIEMBROS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#247]
Tras implementar la tarea #244 se ha incluido el autor del GRUPO en USUARIOS_GRUPO, evitar que aparezca en la vista MIEMBROS tal y como hacía actualmente.

**Comment by profeIAP** [comment]
Adri, esta tarea no se debería implementar: observa que la tengo asignada a mi mismo (lo que supone que está bloqueada)

**Comment by adrivel** [comment]
No sabía que si estabas asignado significa que está bloqueada.

**Comment by profeIAP** [comment]
Acabo de releer una tarea que cogiste estando asignada a Raúl Gómez: recuerda que no puedes coger tareas que ya pertenecen a alguien y, mucho menos, si me pertenecen A MÍ 😝

**Comment by profeIAP** [comment]
Al final la tenía implementada así que la doy por finalizada (y nos quitamos otra tarea "bloqueda" de la lista)
