### ISSUE TITLE
Crear tabla ETIQUETAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#25]
Crear tabla con los siguientes campos:
1. **ID**  campo auto numérico que identificará unívocamente cada entrada.
1. **TEXTO** campo de texto que contendrá el texto de la etiqueta en si.

**Comment by carlosaj98** [comment]
Ya la terminao

**Comment by profeIAP** [comment]
Perfecto Carlos salvo por la falta de ortografía de tu comentario anterior 😒

**Comment by carlosaj98** [comment]
Ya la he terminado

**Comment by profeIAP** [comment]
Pero [no has corregido el comentario inicial](https://github.com/profeIAP/retados/issues/25#issuecomment-284357080) de la "discordia"

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Qué "jartón" de @julioosos quitanto y poniendo tareas.

Cierto y verdad que te di permiso para quitar alguna tarea a @carlosaj98 (por abusón) pero no tiene sentido (salvo el de molestar y/o discutir) hacerlo con la tarea que _realmente_ estaba realizando ¿no os parece?

**Comment by profeIAP** [comment]
Igualmente observo:

1. **model/retados.db** no incluye la tabla ETIQUETAS
1. el script **model/scripts/table_etiquetas.sql** no es correcto (la coma tras el segundo campo hace que no se pueda utilizar)

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Perfecto salvo que, en esta ocasión, no has subido model/retados.db conteniendo la tabla etiquetas

**Comment by carlosaj98** [comment]
Creo que ya la he terminado

**Comment by profeIAP** [comment]
Perfecto Carlos, gran trabajo.
Gracias
