### ISSUE TITLE
Editar el pie de la web

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#29]
Modificar el pie de página actual para que el texto aparezca centrado y el año se calcule automáticamente usando javascript (no queremos tener que modificarlo cada año manualmente y es innecesario).

![captura de pantalla de 2017-03-20 18-00-39](https://cloud.githubusercontent.com/assets/16881846/24111911/407dd3d0-0d98-11e7-8e1f-d64cdc93ed45.png)

**Comment by YellowZaki** [comment]
De nuevo una tarea de vista porque no hay otras disponibles.

**Comment by YellowZaki** [comment]
He puesto el texto de IES Al Andalus dentro del script porque por alguna razón los diferentes <p> aparecen en distintas líneas:

		function EstablecerFecha() {
			var d = new Date();
			var n = d.getFullYear();
			document.getElementById("fecha").innerHTML =  "<strong>Ret{A2}</strong> - (c) " + n + " I.E.S. Al-Ándalus"_;
		}
