### ISSUE TITLE
Crear método listarPreguntas()

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#3]
Crear método que permita recuperar los identificadores y texto de las distintas PREGUNTAS almacenadas en el sistema.

Sirva como referencia el siguiente [fragmento de código](https://github.com/profeIAP/panelDeControl/blob/72b5117f5dcd0f6cb3934d2c637199ae991c1d6f/index.php#L191)

**Comment by profeIAP** [comment]
Se cambia el nombre del método por coherencia con el resto de métodos que estamos definiendo.

**Comment by julioosos** [comment]
Ya esta terminado

**Comment by julioosos** [comment]
.
PD: Perdón se me había olvidado el punto.

**Comment by profeIAP** [comment]
Los puntos se nos olvidan (echaremos la "culpa" a las prisas) hasta al más pintado

Como muestra, te dejo mi frase anterior sin "puntuar".

Buen trabajo Julio, gracias
