### ISSUE TITLE
Obtener aleatoriamente las respuestas de una pregunta

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#31]
Buscar la forma de recuperar las cuatro respuestas de una pregunta de forma totalmente aleatoria (en lugar del orden en el que fueron almacenadas en la BD al ser creadas)

Servirá:

1. implementarlo en el controlador (ordenando el array recuperado)
1. como en el modelo (modificando la sql para que sea SQLite quien cambie la posición de las respuestas en cada consulta )

**Comment by YellowZaki** [comment]
Tengo una ligera idea, hacer una query aleatoria así: 
select id from respuestas order by random() limit 1

**Comment by profeIAP** [comment]
Sería factible pero debes asegurarte que se devuelven las 4 RESPUESTAS (de momento, es posible que en un futuro decidamos incluir más) asociadas a la PREGUNTA que nos interesa

**Comment by YellowZaki** [comment]
He añadido el parámetro $num para que en un futuro se pueda cambiar el número de respuestas que salen.

	public static function listaraleatorio($id,$num){
		$app = \Slim\Slim::getInstance();
		return AccesoDatos::listar($app->db, "RESPUESTAS", "texto", "where $id = 2 order by random() $num");
	}

**Comment by profeIAP** [comment]
Me gusta tu iniciativa pero no será necesraio el parámetro $num: ten en cuenta que debe recuperar "salteadas" las respuestas de la pregunta $id (cambia de paso el nombre del parámetro y **denomínalo $idPregunta** para unificar criterios y evitar confusiones).

Independientemente del número de respuestas que tenga dicha pregunta, las devolverá todas de forma aleatoria ;)

**Comment by YellowZaki** [comment]
Pero el order by random() requiere el número de elementos que va a mostrar, por lo que es necesario. Por defecto sería 4.

**Comment by profeIAP** [comment]
O anidar, como número de elementos, una consulta anidada del tipo: select
count(*) from TABLA where ID_PREGUNTA=$idPregunta 😏

**Comment by YellowZaki** [comment]
Finalmente he entendido lo que significa "anidada". Yo le suelo llamar subconsulta dentro de una consulta.
La verdad es que me parece bien hacerlo así para que no tengamos que tener en cuenta una variable más, de esa manera es automático.

**Comment by profeIAP** [comment]
Grande Alberto, grande... Cada día vas aquiriendo más conceptos, buen trabajo.

Suelen usarse los dos términos indistintamente puesto que las subconsultas (por debajo de la consulta principal) suele anidarse con ésta ;)

**Comment by profeIAP** [comment]
Abro la tarea porque has olvidado eliminar el parámetro "sobrante"

**Comment by YellowZaki** [comment]
Ups, al rato me puse a pensar si había borrado el parámetro y efectivamente lo había olvidado xD

**Comment by profeIAP** [comment]
Fantástico Alberto, funciona perfectamente...¡Gran trabajo!
