### ISSUE TITLE
Cambiar título formulario login

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#32]
Actualmente el layout del login muestra como texto PanelDeControl. Cambiar a Ret{A2}

**Comment by manu21499** [comment]
@profeIAP ya la he hecho la tarea pero no puedo subirla porque no funciona el proyecto. En el momento que arregles el proyecto la subo , voy a cogerme otra tarea para no perder tiempo!!

**Comment by profeIAP** [comment]
Ok, trataré esta tarde (si me devuelven la conexión) dejarlo resuelto.
No obstante tienes una versión de antes del Pleistoceno... te va a costar la misma vida :P

**Comment by manu21499** [comment]
@profeIAP ya he subido la tarea me sale usuario para que sepas que he sido yo . Me haré un git config para que la proxima tarea que suba no me salga usuario :)

**Comment by profeIAP** [comment]
Cómo vas controlando, ¡espectacular!
La tarea está bien y todo, enhorabuena.
