### ISSUE TITLE
Añadir módulo respuestas al proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#33]
Incluir en el proyecto [la librería jQuery Quick-Quiz](https://github.com/UrbanInstitute/quick-quiz) que permite responder a un cuestionario formado por varias preguntas.

Bastará utilizar el json que tienen generado en el github del proyecto (otro se encargará de generar nuestros propios cuestionarios a partir de la BD)

**Comment by Mahc99** [comment]
Terminada :100:

**Comment by profeIAP** [comment]
Algo ha debido quedar atrás Migue porque no me funciona

![imagen](https://cloud.githubusercontent.com/assets/16881846/25527854/0271a5ca-2c1b-11e7-8ff1-c0f76556a95f.png)

**Comment by Mahc99** [comment]
Ya he subido los archivos que me faltaban.

**Comment by profeIAP** [comment]
Simplemente espectacular... ha quedado genial
¡Enhorabuena Migue!

¿¡¿Elegirás un _reto_ o una _"chorrada"_ como tu próxima tarea?!? 😏
