### ISSUE TITLE
Añadir campo "respuestas" a Pregunta::Cargar()

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#35]
Actualmente el método Pregunta::cargar() devuelve, únicamente, los datos de una pregunta (no incluyendo sus respuestas)

Deberás:
1. Hacer una llamada al método Respuestas::listar() para recuperar todas las respuestas de la pregunta actual (usa el $id que te proporcionan para recuperarlas)
1. Añadir al array que se obtiene actualmente tras llamar a AccesoDatos::recuperar(), un nuevo campo (al que llamarás "respuestas") con el resultado del paso anterior

Se etiqueta como _normal_ al tener implementada toda la lógica mencionada anteriormente (salvo añadir un campo a un array en php, que puedes buscarlo en Internet y es sencillo)

**Comment by josufg** [comment]
[Mi 2ª entrada](http://semillerodeempresas.blogspot.com.es/2017/03/la-cosa-va-cogiendo-color.html)

**Comment by josufg** [comment]
@profeIAP Como recordarás el último día dejamos la tarea casi 'finiquitada' pero ahora se me ha borrado todo lo que tenia hecho :/

**Comment by josufg** [comment]
@profeIAP Mientras intento arreglar lo que ha ocurrido voy a ir haciendo otra tarea

**Comment by profeIAP** [comment]
Ok

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Antes de proceder a corregir (que de todos modos no está terminado correctamente) quisiera que se me aclarase [por qué @julioosos decidió quitar la tarea a @josufg](https://github.com/profeIAP/retados/issues/35#event-1030092008).

Igual lo comentamos en clase pero prefiero que quede por escrito y que aparezca el consentimiento del afectado 🤔

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Insisto: ¿qué ha pasado con el "trapicheo" de esta pregunta?

**Comment by profeIAP** [comment]
Tras observar que realmente ha sido implementada por @flobato322 en la tarea #59 cierro esta tarea  asignándomela a mi mismo para que no compute su _supuesta_ realización.
