### ISSUE TITLE
Documentar el envío de emails

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#358]
Utilizando el siguiente[ fragmento de código](https://github.com/profeIAP/retados/blob/8bca7245899aaf6c871ab577e87b9b99107542b8/index.php#L518) (**OJO** cambia el destinatario y ponte tú... no quiero que me lleguen todos los correos de tus pruebas 😏) dejar constancia en un documento de Google Docs de los pasos que hay que dar para que a cualquiera de tus compañeros le funcione el envío de emails.

**NOTA:** no se desarta, si vemos que el trabajo es excesivo, dividir esta tarea en dos de tipo RETO:
1. una por hacerlo funcionar en tu equipo y 
1. otra por documentarlo 

Tu tiempo (,esfuerzo) y dedicación... tienen premio (y te lo agradecemos 👍)

La siguiente [plantilla](https://docs.google.com/document/d/1AChRiNlMCXpeF1mN9xyfI86J0ZBbho4q4BlitMat86g/edit?usp=sharing) te será de utilidad... crea una copia.

**Comment by profeIAP** [comment]
Esta tarea empieza a "enquistarse" sería interesante contar con un "valiente" que la acometa.
Se gratificará generosamente 😇

**Comment by FraniBL** [comment]
le quito esto al carlos porque tiene 2

**Comment by profeIAP** [comment]
Os voy a tener que llamar al orden... ¿tengo realmente que pararme a investigar (incluye el borrado de comentarios) quién es el propietario legítimos de esta tarea?

![](http://abcblogs.abc.es/federico-ysart/wp-content/uploads/sites/45/2015/02/justicia-no-ciega.jpg)

**Comment by profeIAP** [comment]
Carlos, veo que has compartido conmigo un documento en Google Docs (bien hecho) pero recuerda que debe estar enlazado en los comentarios de esta tarea para que todos podamos acceder a él y resulte más sencillo localizarlo.

Cuando consideres que está finalizado, cierra la tarea para que pueda proceder a revisarlo 👍

**Comment by Carjosop** [comment]
[Documentación envio de emails](https://docs.google.com/document/d/1gH1ooveNbDzmER-DknZbDe-dEWw6XPvhZJA1Im0i--c/edit)

**Comment by profeIAP** [comment]
Deben haberte llegado los comentarios que he realizado sobre el documento.
Gracias Carlos

**Comment by profeIAP** [comment]
Incluyo algunas anotaciones en el documento compartido.

Está quedando francamente bien... buen trabajo, Carlos 👍

**Comment by profeIAP** [comment]
Falta por realizar algunas de las sugerencias realizadas en el documento

**Comment by Carjosop** [comment]
Resueltos comentarios documentación

**Comment by profeIAP** [comment]
Se me había pasado completamente corregirlo, perdona Carlos.

Las imágenes ahora sí se ven correctamente (gracias) pero no he podido evitar volver a poner comentarios en el documento (sorry)

**Comment by Carjosop** [comment]
Corregidos los comentarios sugeridos en el documento.

**Comment by profeIAP** [comment]
Bueno, se puede decir que está bastante mejor... como siempre: comentarios en el documento

**Comment by Carjosop** [comment]
Comentarios resueltos

**Comment by profeIAP** [comment]
Juraría haber escrito un "oeeeee, oe, oe, oeeeé...." 😏
