### ISSUE TITLE
Mostrar respuestas en view/pregunta.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#36]
Generar dinámicamente ( bucle {%for ... %} de Twig ) las filas de la tabla de RESPUESTAS con los valores que devuelve la nueva implementación de Pregunta::cargar() (ver tarea #35)

No es especialmente complejo pero requerirá alguna que otra prueba, de ahí que se etiquete como _reto_

**Comment by julioosos** [comment]
Ya está acabada.

**Comment by profeIAP** [comment]
Te incluyo modificación a la vista para que se puedan ver en el formulario el texto de las respuestas.

**Comment by julioosos** [comment]
¿A qué te refieres con que no se marca la correcta?

**Comment by profeIAP** [comment]
Es otra tarea, no sufras...

**Comment by profeIAP** [comment]
Buen trabajo, Julio 👍
