### ISSUE TITLE
Definir entradas del menú opciones MIEMBRO

### ISSUE THREAD

**Issue by gloocc8** [profeIAP/retados#362]
Modificar el menú creado en la tarea #354
![image](https://user-images.githubusercontent.com/16881846/33276877-269b4ef0-d397-11e7-9927-bb807222e64d.png)

para que muestre las opciones siguientes:
1. Contraseña (enlazará a /usuario/proteger)
1. Eliminar (usará el mismo enlace que tiene actualmente el botón de la papelera {{url_del}})
1. Estadísticas (usará el mismo enlace que tiene actualmente el botón de las estadísticas {{url_stat}})

**Comment by profeIAP** [comment]
Fantástico Frani peeerroooo haya pequeños despistes en la implementación:

1. La opción para cambiar la contraseña no usa la url pedida
1. Se observan faltas de ortografía en las opciones del menú

![image](https://user-images.githubusercontent.com/16881846/33441337-bd5d3dc8-d5f2-11e7-85bb-f7722346dc55.png)

**Comment by profeIAP** [comment]
Fantástico Frani, buen trabajo.
Gracias
