### ISSUE TITLE
Solicitar nueva clave de USUARIO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#363]
Mostrar ventana pop-up (similar a [la usada al crear un TEMA](https://github.com/profeIAP/retados/blob/0054a0f6b4d2073916cf50bfdb694bf44ffee4a8/view/grupo-temas.php#L79)) en el botón "Cambiar contraseña" de un MIEMBRO de nuestro GRUPO de ALUMNOS.

**Comment by profeIAP** [comment]
Raúl, ¿has probado que realmente pide la nueva contraseña?

**Comment by profeIAP** [comment]
Espectacular Raul pero recuerda que, como se indica en la descripción de la tarea, el formulario debe invocarse desde el botón "Cambiar contraseña" de un MIEMBRO de nuestro GRUPO de ALUMNOS (y no desde TEMAS como ocurre actualmente).

Aprovecha para cambiar el mensaje por "Indique la nueva contraseña del usuario"

Gracias "monstruo" 👍

![image](https://user-images.githubusercontent.com/16881846/33441783-ca2bb538-d5f3-11e7-848a-8a061f3a6faa.png)

**Comment by profeIAP** [comment]
La abro porque no encuentro el cambio que hicimos esta mañana (a pesar de haberlo visto)
Imagino que no te habrá dado tiempo de subir los cambios; ya lo aclaramos

**Comment by Rgm13** [comment]
Que cambio era, el de la ventana pop-up en el boton cambiar contraseña de miembros?

**Comment by profeIAP** [comment]
El que [se te pedía en el siguiente comentario](https://github.com/profeIAP/retados/issues/363#issuecomment-348242030)

No obstante, faltan los cambios que hemos hecho (otra vez) esta mañana en tu equipo que permiten que salga el pop-up (solicitando la nueva contraseña) desde el menú que hemos creado

![image](https://user-images.githubusercontent.com/16881846/33560102-10e217ce-d90f-11e7-963f-4c4e0aad2b2c.png)

**Comment by Rgm13** [comment]
Que extraño en mi equipo se veian todos los cambios correctamente y recuerdos haberlos subido bien.
Ya los volvere a subir el lunes

**Comment by profeIAP** [comment]
Efectivamente: es raro.

Estoy convencido que no se han subido los cambios (push) de ahí que tú los veas y el resto "de la Humanidad" no 😉

**Comment by profeIAP** [comment]
Perfecto Raúl... muy buen trabajo.
