### ISSUE TITLE
Crear clase Registro

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#364]
Crear el fichero controller/Registro.php.

Su implementación será [similar a controller/Estadisticas.php](https://github.com/profeIAP/retados/blob/0054a0f6b4d2073916cf50bfdb694bf44ffee4a8/controller/Estadisticas.php#L3) pero:
1. Cambiando el nombre al fichero (controller/Registro.php)
1. Cambiando el nombre de la clase de Estadisticas a Registro

**NOTA:** elimina sin miedo los dos métodos que incluye la clase Estadisticas (ya crearemos los nuestros propios, no temas)

**Comment by profeIAP** [comment]
Abro la tarea pues, aunque lo hemos hablado (y se indica en la descripción de la tarea), has olvidado borrar los dos métodos "sobreros".
Es poca cosa y estaba casi convencido que lo habías hecho... ¿has podido confundirte al hacer el commit?

**Comment by FraniBL** [comment]
El problema fue que en mi primer commit borré los dos métodos de estadísticas.php en lugar de registro.php (Muy inteligente por mi parte)

Así que hice otro commit borrándolos de registro, y otro para volver a ponerlos en estadísticas, ya que no le había dado cuenta. No estoy seguro, pero creo que está bien.

**Comment by profeIAP** [comment]
Ahora sí está perfecto, gracias Frani 👍
