### ISSUE TITLE
Crear método Cuestionario::generar(numPreguntas)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#37]
Añadir a la clase Cuestionario un método, al que llamaremos _generar_ cuya finalidad será:

1. Llamar a **Pregunta::sortear()** para obtener _numPreguntas_ al azar (ver tarea #34)
1. Llamar a **Cuestionario::toJSON()** para que devuelva las preguntas obtenidas en el paso anterior a un JSON que sea interpretable por el componente que permite al usuario responder a las preguntas (ver tarea #38).

**NOTA:** se etiqueta como _normal_ pues se limita a delegar en otras clases lo que debe ir haciendo.

**Comment by carlosaj98** [comment]
Creo que ya la he terminado

**Comment by profeIAP** [comment]
Casi... has olvidado tanto incluir (como utilizar) el parámetro $numPreguntas en el método

**Comment by carlosaj98** [comment]
Creo que ya la he terminado

**Comment by profeIAP** [comment]
Como no has podido probar lo que has hecho (normal hasta que el resto de tus compañeros implementen los métodos que te hacen falta) no te has dado cuenta que el método no está devolviendo (return) absolutamente nada.

Como comentamos en clase, debes devolver el resultado de invocar a _Cuestionario::toJSON($preguntas);_

**Comment by carlosaj98** [comment]
Ya la he terminado

**Comment by profeIAP** [comment]
Siento disentir:

1. sorteas (innecesariamente) dos veces las preguntas
1. recoges el resultado de Pregunta::sortear() en una variable (a la que llamas $p) y pides que te conviertan a JSON otra variable que no tiene contenido ($preguntas)

Mañana no podremos volver a hablar... ponte a pensar ~de una vez~ 😒😂

**Comment by carlosaj98** [comment]
Creo que ya

**Comment by profeIAP** [comment]
Efectivamente, ahora está perfecto.
Enhorabuena Carlos, espero que haya servido para comprender (por fin) cómo gesiontar las variables y los parámetros en el código
