### ISSUE TITLE
Crear método Cuestionario::toJSON($preguntas)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#38]
Crear método que permita, dado un array de PREGUNTAS [ como los que devuelve Pregunta::cargar() o Pregunta::sortear() ], devolver un JSON con el resultado de serializar el contenido de las PREGUNTAS y RESPUESTAS en [el formato esperado](https://github.com/UrbanInstitute/quick-quiz/blob/master/unicorns.json) por el componente jQuery de la tarea #33

**Comment by josufg** [comment]
@profeIAP Espero que mañana quede finiquitado, ya voy aprendiendo la mecánica de los métodos.

**Comment by profeIAP** [comment]
La práctica hace al maestro Josu 😉

**Comment by josufg** [comment]
@profeIAP Sino sugieres algún error o cambio la cierro

**Comment by profeIAP** [comment]
Está francamente bien Josué pero observa que falta (para dar por finalizada la implementación) transformar el JSON que has generado en el formato que espera nuestro componente para renderizar cuestionarios (ver enlace en la descripción de la tarea)

Si te parece, tratamos cómo abordar dicha solución 👍

**Comment by josufg** [comment]
@profeIAP Perfecto

**Comment by josufg** [comment]
@profeIAP Debo generar un ejemplocuestionario.php? Si es así, debo invocarlo desde el controlador o desde el index?

**Comment by profeIAP** [comment]
No. Bastará que exista (y funcione correctamente) el Cuestionario::toJSON($preguntas)

Si quieres dejar un GET:/json en index.php no hay problemas pero será eliminado tan pronto se compruebe el correcto funcionamiento de tu implementación.

**Comment by profeIAP** [comment]
Josu, estoy a punto de quedarme con esta tarea pues llevas con ella desde hace más de 21 días.

Te libras porque la Semana Santa ha estado de por medio y confío en que podrás llevarla a cabo pero estate atento, tiene más aristas de lo que en un principio puedes sospechar.

Como máximo te dejaré con ella hasta el próximo viernes pero igual te compensa centrarte en tareas más sencillas que te permitan ir adquiriendo puntos "de experiencia"

**Comment by josufg** [comment]
public static function toJSON($preguntas){
		$rsdo="{";
		$preguntas as $p;
		echo json_encode($p);
		"}"
}

**Comment by josufg** [comment]
@profeIAP ¿Así sería el bucle?

**Comment by profeIAP** [comment]
Ni de lejos, te has limitado a transcribir lo que había en el papel de mis explicaciones.

Haz uso del foreach, tenemos un [ejemplo aquí](https://github.com/profeIAP/retados/blob/master/controller/Pregunta.php#L56)

**Comment by josufg** [comment]
@profeIAP Oki doki. A ver si puedo dejarla lista para el viernes

**Comment by profeIAP** [comment]
Aunque está prácticamente terminado no creo que el ćodigo (a pesar de existir un método GET para ello) haya sido probado:
1. index.php no incluye la clase Cuestionario (para que pueda ser usada)
1. Cuestionario.php contiene errores que no permiten que compile correctamente (se han olvidado algunas llaves y/o se han borrado)

**Comment by josufg** [comment]
@profeIAP Supuestamente ya está todo correcto. Si haces el GET:/cuestionario, te lo lanza.

**Comment by profeIAP** [comment]
Te he corregido algunas cosas y añadido un comentario sobre el propio commit que has realizado.

**Comment by josufg** [comment]
@profeIAP Perfecto, muchas gracias profe

**Comment by josufg** [comment]
@profeIAP Tras tus arreglos el método ya está listo. Gracias

**Comment by profeIAP** [comment]
No me suelo portar "mal" pero tampoco tan bien como para hacerlo yo mismo 😏
Recuerda [resolver este problema](https://github.com/profeIAP/retados/commit/38b206e0516d622f2303227467eba5a97ad451c7#diff-4e1affc1928016a87719ee6bcde42dd8R15)

**Comment by profeIAP** [comment]
Lo siento Josué pero al final la voy a implementar yo porque empieza a ser crucial contar con ella y ha pasado demasiado tiempo.
