### ISSUE TITLE
Evitar se vea la clave asignada a un MIEMBRO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#386]
Cambiar la [configuración de Sweet Alert](https://github.com/profeIAP/retados/blob/24a189c051237b46ed2c972cb9a2071d9bdf186c/view/grupo-temas.php#L70-L75) en la siguiente línea para que oculte (los típicos asteriscos) la contraseña que estamos asignando a un MIEMBRO del GRUPO

![image](https://user-images.githubusercontent.com/16881846/33441898-1bde74c4-d5f4-11e7-80dd-6eb1ef60863e.png)

Debería servir [el siguiente truco](https://github.com/t4t5/sweetalert/issues/314#issuecomment-83644548), en caso de no ser la solución, podría subirse la recompensa por resolver el problema 👍

**Comment by profeIAP** [comment]
Lo siento Inma... es posible que no hayas subido los cambios (push) al servidor.
Actualmente siguie viéndose la clave tal y como aparece en la imagen que acompaña la descripción de esta tarea.

**Comment by profeIAP** [comment]
Desgraciandamente (y con el commit último), sigue sin funcionar

![image](https://user-images.githubusercontent.com/16881846/34114578-704877bc-e413-11e7-93e5-f7f448ff86e1.png)

**Comment by Inmaghibli00** [comment]
pero,¿ me pide que oculte los asteriscos no? yo misma lo probé la semana
pasada y me funcionó

2017-12-18 16:49 GMT+01:00 Profesor IAP <notifications@github.com>:

**Comment by profeIAP** [comment]
Perfecto Inma, buen trabajo.
