### ISSUE TITLE
No llega valor textArea a POST:/preguntas/guardar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#39]
Se observa que actualmente no está llegando el contenido del textarea en el que se indica la PREGUNTA que queremos realizar.

Puede deberse a múltiples motivos pero todo apunta a que se trata de un fallo de Utilidades::getDatosFormulario()

_Recomendaría_ mirar si el formulario está enviando dicha información en el momento de pulsar el botón (inspeccionando la vista y observando qué se envía desde la pestaña Network del navegador) 

**OJO:** esta tarea, aunque etiquetada como _reto_, puede ser una auténtica tortura por lo que no se aceptarán reclamaciones en caso de invertir más tiempo del considerado lógico y no obtener ningún tipo de recompensa ¡Estás avisado!

**Comment by Patriexd** [comment]
ya está arreglado, pero para que funcione requiere que se procese

**Comment by profeIAP** [comment]
¿Qué debe procesarse?

No entiendo lo que quieres decir @Patriexd (sorry)

**Comment by Patriexd** [comment]
me dijiste que te excribiese eso para que te acordaras de no se que, preguntate a tu yo del pasado @profeIAP

**Comment by profeIAP** [comment]
Menos mal que existe ese yo del pasado y no tiene demasiada mala memoria (al menos, no peor que la tuya 😏

Modificaré controller/Pregunta.php para que todo fluya como es debido y no s produzcan errores indeseados (por falta de coordinación)

Damos por cerrada la tarea, gracias Patri
