### ISSUE TITLE
Centrar botón opciones en view/grupo-alumnos.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#392]
Reducir el tamaño de la columna (cambiando el atributo _width_ de la cabecera de la tabla a su "mínima expresión") y centrar el icono de la "hamburguesa" para que se muestre adecuadamente en su celda.

![image](https://user-images.githubusercontent.com/16881846/33560805-15008514-d911-11e7-9230-d2c13fb449bb.png)

**Comment by juankagb00** [comment]
Hay un error

**Comment by profeIAP** [comment]
Tras ver que no es tan sencillo como cambiar el atributo _align_ subimos el nivel de dificulta de la tarea.

**Comment by profeIAP** [comment]
Esta tarea está dando más problemas de los deseables por lo que se opta por quitarla del milestone actual

**Comment by profeIAP** [comment]
Centrado, lo que se dice centrado... no está

![image](https://user-images.githubusercontent.com/16881846/39856348-ccddbbcc-542f-11e8-8010-926ed4b74645.png)

**Comment by profeIAP** [comment]
Benji, sigo sin ver el cambio solicitado en la tarea (amén de que has incuido algunos ficheros que dudo que sea "pertinente" incluir)

**Comment by profeIAP** [comment]
Fantástico Benjamín, está perfecto.
Ahora te pido tu "experta" opinión: ¿crees que sería factible centrarlo también verticalmente? (para crear una nueva tarea y premiar dicho esfuerzo 😉)

![image](https://user-images.githubusercontent.com/16881846/40126194-07929c54-592d-11e8-9e84-18ba43c553b5.png)

**Comment by benjigar** [comment]
Lo sería
