### ISSUE TITLE
Incluir librería de notificaciones

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#396]
Añadir la posibilidad de mostrar mensajes de aviso al USUARIO en cualquier momento.

Existen [infinidad de librerías jQuery que lo implementan](https://www.jqueryscript.net/tags.php?/Notification/) de las que me ha llamado la atención [jQuery lobibox](https://www.jqueryscript.net/demo/Responsive-jQuery-Message-Box-Notification-Plugin-lobibox/) (siéntete libre de elegir cualquier otra si te gusta más pero comenta de cuál se trata antes de hacerlo)

![image](https://user-images.githubusercontent.com/16881846/33565996-fd457d5e-d91e-11e7-81bd-ced67505314e.png)

Tu **objetivo** será incluir las librerías javascript y hojas de estilo CSS necesarias en view/layout.php y demostrar que funciona correctamente.

**Comment by profeIAP** [comment]
La [web oficial en gitHub](https://github.com/arboshiki/lobibox) del proyecto

**Comment by JesusLG11** [comment]
Código a lanzar desde la consola del navegador para probar la tarea

> Lobibox.notify('error',
> {
>                     size: 'mini',
>                     title: 'Lorem ipsum',
>                     msg: 'Lorem ipsum dolor sit amet hears farmer indemnity inherent.'
> });

**Comment by profeIAP** [comment]
Fantástico Jesús, ha quedado espectacular ¡Gracias!

![image](https://user-images.githubusercontent.com/16881846/34047839-e2308298-e1b1-11e7-9e25-24b8a35a78aa.png)

No obstante, observo que has duplicado innecesariamente librerías que pueden estar provocando que haya dejado de funcionar el editor WYSIWYG tanto en pregunta.php como en la configuración del grupo

![image](https://user-images.githubusercontent.com/16881846/34048038-81bc5fd0-e1b2-11e7-9e25-f6355a4ffb91.png)

**Comment by profeIAP** [comment]
Ahora sí... gran trabajo Jesús.
Gracias
