### ISSUE TITLE
Mejorar la gestión de logs

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#397]
Sustituir todas las [llamadas a error_log()](https://github.com/profeIAP/retados/blob/43c1209336f8134b3c6b0a381530ff58f5d3a808/index.php#L176) del proyecto por Logger (aquí un [ejemplo de uso](https://github.com/profeIAP/panelDeControl/blob/72b5117f5dcd0f6cb3934d2c637199ae991c1d6f/index.php#L702))

**NOTA:** se etiqueta como _reto_ mas por el tiempo que se dedicará a buscar y sustituir en todos los ficheros del proyecto (index.php mas las clases existentes en la carpeta _controller_) que por la complejidad que entrañe.

Se recomienda usar la siguiente opción de búsqueda (CTRL+F) para no dejar ningún error_log atrás

![image](https://user-images.githubusercontent.com/16881846/33567128-6fecbbee-d922-11e7-96c0-196e01ae7755.png)

**Comment by profeIAP** [comment]
Muy bien hecho Gloria pero, como se indica en la descripción de la tarea, debe cambiarse **en el proyecto** completo (y no sólo en _index.php_)

Observa que aparecen llamadas a _error_log_ en los siguientes ficheros del proyecto 😅

![image](https://user-images.githubusercontent.com/16881846/33949053-b84b05c8-e028-11e7-807d-5db509be31d0.png)

**Comment by profeIAP** [comment]
Espectacular Gloria, buen trabajo

**Comment by gloocc8** [comment]
Bueno maestro con esto subo nota no?

**Comment by profeIAP** [comment]
Claro que subes nota Gloria... pero te voy a pedir un "favor": cuando contestes desde el móvil borra todo el mensaje y deja sólo lo que quieres comentar para evitar "basurilla" ;)

![image](https://user-images.githubusercontent.com/16881846/34052157-7ed3b624-e1c1-11e7-8ace-6f96f484aa40.png)
