### ISSUE TITLE
Alinear a la derecha el número de PREGUNTA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#399]
El número de PREGUNTA (implementado en la tarea #378) quedará mejor si aparece alineado a la derecha

![image](https://user-images.githubusercontent.com/16881846/33948639-a91e9bec-e027-11e7-9d9b-11c7943c1713.png)

**Comment by gloocc8** [comment]
Confundí el número de tarea. Esta se implementó en el commit 4927e9e923fcc5f796d7a30529d2de5c6a12892f

**Comment by profeIAP** [comment]
Muy buen trabajo, Gloria 👍

![image](https://user-images.githubusercontent.com/16881846/34052108-43345b0a-e1c1-11e7-9f84-bcc265dff937.png)
