### ISSUE TITLE
Crear método Respuesta.listar(idPregunta)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#4]
Crear método que permita recuperar todos los datos de las distintas RESPUESTAS almacenadas en el sistema asociados a la PREGUNTA cuyo id (idPregunta) se especifica como parámetro de entrada.

Sirva como referencia el siguiente [fragmento de código](https://github.com/profeIAP/panelDeControl/blob/72b5117f5dcd0f6cb3934d2c637199ae991c1d6f/index.php#L191).

**Comment by profeIAP** [comment]
Cambio el nivel de dificulta por acordar crear una clase controller/Respuesta y tener que crear el group('/respuestas') en index.php

**Comment by julioosos** [comment]
maestro acuerdate que esta es mía, suelto esta tarea para implementar el where

**Comment by profeIAP** [comment]
Creo que voy a tener "amnesia selectiva" mientras no corrijas las faltas del comentario anterior. 
Igualmente, estaría francamente bien, que pusieses referencia a la tarea que has elegido (por la almohadilla "#" y el número de tarea correspondiente) para que todo quede realmente "clarito" y cómodo de leer (dentro de unos días no sabremos ni de lo que estamos hablando 😅)

**Comment by profeIAP** [comment]
Quito la asignación a @jcarlos99 _"en lo que"_  @julioosos corrige su "perífrasis"

**Comment by profeIAP** [comment]
@julioosos, al final he terminado yo la tarea #26 (que pertenecía a @manu21499)

Al pertenecer al milestone 0.1, debes acabar su implementación en el menor tiempo posible pues _quiero concederte la oportunidad_ de demostrar que controlas lo que hay que hacer antes que opte por implementarla directamente yo.

No aceptaré "reclamaciones": o se hace pronto o la hago yo 😏 ¡Enfoca!

**Comment by julioosos** [comment]
ya esta terminada.He hecho el commit a la tarea #4 por equivocación me referia a esta tarea

**Comment by profeIAP** [comment]
Y funciona perfectamente, gran trabajo Julio.
