### ISSUE TITLE
Editar PREGUNTA pinchando en su descripción

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#400]
Añadir enlace ([idéntico al usado en el botón editar](https://github.com/profeIAP/retados/blob/ac5c70a1b819f67c4a16bfa42e5f56e195e41320/view/preguntas.php#L61) que hay en la derecha de la tabla) que permita acceder rápidamente a la edición de la PREGUNTA simplemente pinchando sobre el texto de la misma

![image](https://user-images.githubusercontent.com/16881846/33951579-a1fe011a-e02f-11e7-9693-65658d9681a2.png)

**Comment by profeIAP** [comment]
Aunque ya tenemos enlaces en las descripciones de las PREGUNTAS (enhorabuena, ha quedado francamente bien)

![image](https://user-images.githubusercontent.com/16881846/34048570-7892cd52-e1b4-11e7-8666-f10768c60a16.png)

resulta imposible usarlos. 

Añado comentario en el propio commit para que puedas ver dónde está el problema.

**Comment by Rgm13** [comment]
Cuando pinchas en la pregunta no se te redirecciona a la página para editar las preguntas?

**Comment by profeIAP** [comment]
Mil perdones @Rgm13 acabo de ver que el problema lo ha introducido @juankagb00 al poner el menú en la tarea #401

**Comment by juankagb00** [comment]
Maestro pues yo comprobé antes de subirlo y iba bien.

**Comment by profeIAP** [comment]
No lo dudo (y me alegra que ya empieces a comprobar las cosas antes de subir al repositorio... estás mejorando mucho y no todos lo hacen **todavía** 😉)

Lo he dejado corregido: era un detalle muy "fino" como para que te hubieses dado cuenta... no sufras 👍
