### ISSUE TITLE
Crear plantilla email recuperar contraseña

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#404]
Crear una [vista similar a view/emailSiNo.php](https://github.com/profeIAP/retados/blob/00188d278c553a250cf003736cfbc94574f72f4e/view/emailSiNo.php) para poder enviar correos al usuario con el enlace que deberá utilizar para recuperar su contraseña.

Dicha plantilla deberá respetar la siguiente estructura

![image](https://user-images.githubusercontent.com/16881846/34161285-81e167dc-e4d0-11e7-84d7-7db70d57e5de.png)

No te preocupes por el texto "Hemos recibido...", en dicha celda sólo debes añadir la etiqueta {{mensaje|raw}} (ya se le proporcionará el texto a mostrar, no es tarea tuya)

**NOTA 1:** el botón "Cambiar contraseña" invocará el método GET:/usuario/restablecer
**NOTA 2:** guardar el formulario en view/emailRecuperarClave.php

**Comment by profeIAP** [comment]
Será de especial utilidad el siguiente [editor online de tablas HTML](https://www.froala.com/wysiwyg-editor/examples/table-styles)

**Comment by profeIAP** [comment]
@Carjosop, vamos a simplificar la plantilla: pondremos una sola columna en la que la primera fila será para el icono del proyecto y las restantes serán el texto y el botón.

De este modo creo que quedará estéticamente mejor si el email se abre en un móvil y te va a simplificar su implementación.

**Comment by profeIAP** [comment]
Carlos, algo se nos ha tenido que escapar porque:
1. en el commit que has subido no aparece view/emailRecuperarClave.php
1. no existe el fichero view/emailRecuperarClave.php
Lo revisamos el próximo día, ¿te parece?

**Comment by profeIAP** [comment]
Está perfecto Carlos salvo que echo de menos el botón "Cambiar contraseña" que debe tener el formulario solicitado

![image](https://user-images.githubusercontent.com/16881846/35395556-f6ff8558-01ea-11e8-9d68-0d1c17619fcd.png)

**Comment by profeIAP** [comment]
Está casi perfecto pero te has confundido al poner el texto del botón (debes ponerlo a "piñón", no te lo pasarán como una variable)

![image](https://user-images.githubusercontent.com/16881846/35518878-1030b666-0513-11e8-84f5-98fdcfd7ccd8.png)

**Comment by profeIAP** [comment]
Qué te gustan las "llaves", Carlos... el error sigue siendo el mismo y el motivo por el que aparece (aunque has cambiado levemente el código) sigue persistiendo 😏

**Comment by Carjosop** [comment]
Eliminadas las llaves.

**Comment by profeIAP** [comment]
Oeeee, oe, oe, oeeee...
