### ISSUE TITLE
Invocar POST:/temas/compartir en view/grupo-temas.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#431]
Completar la [opción de compartir un TEMA](https://github.com/profeIAP/retados/blob/47bf080b68978756b0f79116267771ba4b3b98a2/view/grupo-temas.php#L162) con una [implementación similar](https://github.com/profeIAP/retados/blob/47bf080b68978756b0f79116267771ba4b3b98a2/view/grupo-temas.php#L89-L96) a esta pero que invoque el método POST:/temas/compartir

**Comment by profeIAP** [comment]
¿Por qué sospecho que esta tarea en la misma que está haciendo @FraniBL en la #422?

**Comment by Rgm13** [comment]
Y ahora que?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Rgm13** [comment]
Y ahora que?

**Comment by profeIAP** [comment]
Abro la tarea tras comprobar que has metido "basurilla" en el commit (añado comentario para que puedas apreciarlo en todo su "esplendor")

**Comment by profeIAP** [comment]
Me vas a volver medio "tarumba" Raúl, el último commit no hace referencia a esta tarea (sino a los cambios en los nombres de los métodos "get" de Confirmaciones. 

No obstante, parece que el código es correcto aunque, claro, igual lo ha implementado @FraniBL 😏
