### ISSUE TITLE
Crear método Confirmacion::recuperar($hash)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#440]
Crear el método indicado (similar al desarrollado en #434) que, dado un código $hash:
1. Obtenga de la tabla Confirmación de la BD la entrada con el campo CONFIRMACION.HASH = $hash
1. Utilizando el constructor de la clase Confirmacion ( #439) y los datos recuperados, devuelva un objeto de tipo Confirmación

**Comment by profeIAP** [comment]
Te dejo anotado [cómo instanciar un objeto en PHP](http://shodor.org/~kevink/phpTutorial/zacharys_objects.php)

**Comment by profeIAP** [comment]
Es más que posible que funcione pero, el uso incorrecto de una llave, ha provocado que deje de ser un método de la clase

![image](https://user-images.githubusercontent.com/16881846/35810915-77e32ca6-0a8d-11e8-86c1-ee1c0d8c1ebd.png)

**Comment by profeIAP** [comment]
Al igual que [le ocurrió a @gloocc8](https://goo.gl/N2LTV4), falta declara el objeto $app

**Comment by profeIAP** [comment]
Añado comentario al commit

**Comment by JesusLG11** [comment]
cerrada

**Comment by profeIAP** [comment]
Perfect, gracias Jesús
