### ISSUE TITLE
Añadir campo PREGUNTAS.ETIQUETAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#46]
Añadir campo ETIQUETAS (de tipo texto) a la tabla PREGUNTAS.
Recuerda que:

1. Debes **actualizar el script** de dicha tabla en la carpeta _model/scripts_
1. El **campo** _ID_ debe seguir siendo de tipo **autoincremento**

**Comment by profeIAP** [comment]
Jesús, abro la tarea hasta que recuperes el ON DELETE CASCADE que se implementó en la #6 y que se nos ha "perdido" (el encargado de eliminar todas las RESPUESTAS asociadas a la PREGUNTA borrada)

**Comment by profeIAP** [comment]
Has metido "ruido" en  [model/scripts/table_preguntas.sql](https://github.com/profeIAP/retados/commit/40cdead415146ea2c82f11ff8383b4f985b61942) y seguimos sin tener el ON DELETE CASCADE.

¿A la tercera irá la vencida?

**Comment by j1m1** [comment]
Ya te he dicho en clase que el ON DELETE CASCADE no existía en la tabla PREGUNTAS, Balbuena que fue el que lo hizo lo implementó en la tabla RESPUESTAS. 
Insertar el ON DELETE CASCADE en PREGUNTAS sería otra tarea distinta a la que hemos hecho Don Rafael y yo. Salu2

**Comment by profeIAP** [comment]
Siendo así, me dedicaré a buscar quién ha "borrado" el ON DELETE CASCADE para exigir su reposición.

No obstante, para poder dar por válida esta tarea, exigiré que elimines la "basurilla" que introdujiste en [model/scripts/table_preguntas.sql](https://github.com/profeIAP/retados/commit/40cdead415146ea2c82f11ff8383b4f985b61942)

**Comment by profeIAP** [comment]
D. Jesús, ha quedado aclarado el "misterio": funciona perfectamente pero se nos ha olvidado (a pesar de que lo dejé documentado en la tarea #6) que [es necesario lanzar una sentencia pragma para que se aplique el ON DELETE CASCADE](https://github.com/profeIAP/retados/blob/1b8c5ecd9c7caf718a844ba288a08f39cd4defd5/index.php#L73) 

Lo dejo aquí documentado por si nos sirve de "escarmiento" (a mi el primero) y la próxima vez nos acordamos alguno de los dos 😅

**Comment by profeIAP** [comment]
Gracias Jesús, buen trabajo 👍
¡Vamos por la siguiente tarea!
