### ISSUE TITLE
Crear SQL que cuente el uso de cada ETIQUETA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#47]
Crear SQL (que se almacenará en _/model/scripts/sql_etiquetasNumeroUsos.sql_) que indique (de la tabla ETIQUETAS) en cuántas PREGUNTAS (utiliza un like %..% sobre el campo PREGUNTAS.ETIQUETAS que se ha creado en la tarea #46 ) es utilizada cada ETIQUETA

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Desgraciadamente no termina de funcionar, hay que pulir algunos detalles

**Comment by profeIAP** [comment]
A pesar de las "amenazas" de hoy y, teniendo en cuenta que la semana pasada fue "feriado" no considero justo abordar esta tarea hasta el próximo viernes pues "sólo" ha tenido una semana para llevarla a cabo 😏
