### ISSUE TITLE
Crear trigger al insertar PREGUNTAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#48]
Crear trigger que, al insertar una PREGUNTA, se asegure que no existen ETIQUETAS duplicadas lanzando la SQL de la tarea #45

**Comment by Patriexd** [comment]
¿Qué tengo que hacer esta tarea?

**Comment by profeIAP** [comment]
De momento, esperar a que esté lista la tarea #45 😏

**Comment by Patriexd** [comment]
¿y después?

**Comment by profeIAP** [comment]
Llamar a la SQL de la tarea indicada (que se encargará de eliminar todo lo que esté duplicado)
Ve mirando la creación de triggers en SQLite ON INSERT, mientras tanto cogería otra tarea porque sospecho que su autor va a tardar un ratito en lograr tenerlo funcionando

**Comment by profeIAP** [comment]
Fran, como has llegado después de Josué, te quito la asignación

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Y bien terminada que está... simplemente espectacular.
Gracias Carlos
