### ISSUE TITLE
Añadir icono de disputa en la ventana que notifica una respuesta incorrecta

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#484]
Modificar el fichero js/quiz.js de modo que aparezca el icono de la tarea #483 en la esquina superior izquierda.

![image](https://user-images.githubusercontent.com/16881846/36275881-6e2f33c4-128c-11e8-875f-ce6541558add.png)

**Comment by Carjosop** [comment]
Me he equivocado al cerrar tarea

**Comment by profeIAP** [comment]
Casi, no termina de verse la imagen (cuida la ruta)

![image](https://user-images.githubusercontent.com/16881846/36551767-a8b8782c-17f8-11e8-9762-ae9d44801438.png)

Aprovecha la ocasión para separa el icono un poco del texto

**Comment by profeIAP** [comment]
Como hemos comentado en clase, el icono no debería llamar tanto la atención (no queremos una "avalancha" de reclamaciones ¿verdad?) 

![image](https://user-images.githubusercontent.com/16881846/36586275-7261c3a8-1881-11e8-98ad-76faa6425b38.png)

**Comment by profeIAP** [comment]
Estupendo Carlos, buen trabajo.

Otra cosa es que el icono buscado por @gloocc8 no termina de verse bien (tal y como has comentado en clase hoy) a tan pequeña resolución.

De momento lo daremos por bueno, gracias
