### ISSUE TITLE
Crear trigger al actualizar PREGUNTAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#49]
Crear trigger que, al hacer un _update_ de una PREGUNTA, se asegure que no existen ETIQUETAS duplicadas (lanzando la SQL de la tarea #45) y que no queden etiquetas que NO estén siendo usadas en las PREGUNTAS (haciendo un _delete_ de todas las ETIQUETAS devueltas por la SQL de la tarea #63 )

**Comment by profeIAP** [comment]
Un interesante (y completo) [tutorial sobre triggers](http://www.sqlitetutorial.net/sqlite-trigger/)

**Comment by YellowZaki** [comment]
Listo, solo falta esperar que la tarea #47 esté terminada. Pongo lo que llevo por ahora (lo he comprobado y funciona bien):
CREATE TRIGGER asterisco after update on preguntas BEGIN delete from etiquetas where id in (select distinct n1.id from etiquetas as n1, etiquetas as n2 where n1.TEXTO = n2.TEXTO and n1.ID > n2.ID); **SENTENCIA2 DE LA TAREA #47**; END;

**Comment by profeIAP** [comment]
No termina de estar bien el principio del trigger pero imagino que se debe a haberlo copiado incorrectamente ¿conseguiste hacer funcionar la prueba de los "asteriscos" que te plantee? 😏

He optado por crear la tarea #63 para que quede más limpio el trigger que estás creando.

**Comment by YellowZaki** [comment]
A mí me crea bien el trigger. Y se ejecuta la sentencia de la tarea #45 al actualizar la pregunta.

	CREATE TRIGGER onupdatepregunta after update on preguntas BEGIN delete from etiquetas where id in (select distinct n1.id from etiquetas as n1, etiquetas as n2 where n1.TEXTO = n2.TEXTO and n1.ID > n2.ID); END;

**Comment by profeIAP** [comment]
Y tienes toda la razón del mundo: ha sido el nombre que has puesto al trigger (**onupdatepregunta**) el que me ha confundido.

Normalmente tendemos a denominarlos **trg_preguntaUpdate** pero no tenías por qué saberlo ya que es el primero que se ha creado este año.

Quedamos a la espera de finalizar la tarea #47 (sea quien sea el que lo haga 😜)

**Comment by profeIAP** [comment]
@YellowZaki recuerda terminar esta tarea... la #47 la terminé en su día y falta cerrar esta.

**Comment by profeIAP** [comment]
Que sepas que este viernes, la tarea será mía 😇

**Comment by YellowZaki** [comment]
Para completar la tarea necesito eliminar lo obtenido por la consulta a una vista, cosa que es imposible.

**Comment by profeIAP** [comment]
Sospecho que lo estás enfocando mal, Alberto.

Como bien dices, de la vista no se puede borrar nada: deberás hacerlo de la tabla, utilizando de la vista, los datos que debes borrar.

Si te parece lo hablamos mañana y así aprovechamos tu potencial (aunque te honra querer resolverlo por tus medios y estás aprendiendo muchísimo más de lo que te podría enseñar, me "duele" verte pegando cabezazos y que no optes por preguntarme aunque te "insista" en clase 😏)

**Comment by YellowZaki** [comment]
Pues he conseguido hacerlo XD. Iba bien (estaba intentando hacer una subquery) pero me daba error de que no se podia obtener como resultado más de 1 row así que he cambiado el * de la subquery por el campo texto.

Esta es la sentencia para borrar las etiquetas no usadas:
delete from etiquetas where texto in (select texto from etiquetascontador where NUM_USOS=0)

Ahora solo queda meterlo en el trigger y listo.

**Comment by YellowZaki** [comment]
Buscando entre las issues algún ejemplo sobre donde subir el trigger creado, he visto que en el commit https://github.com/profeIAP/retados/commit/0e1c11fa0f076600229ab3da81c56a2f00ae3f00 ya casi solucionaste la tarea esta solo que en dos triggers (y he podido comprobar que el borrado de etiquetas no usadas que he hecho es correcto, prometo que no lo miré XD).
Ahora ya subo la tarea completa.

**Comment by profeIAP** [comment]
No trates de excusarte "todos" sabemos que ~has hecho trampa~ tienes capacidad para éso y para más 👍

Sólo te falta subir una versión actualizada de _model/retados.db_ que incluya el trigger que has creado.

Gracias Alberto

**Comment by YellowZaki** [comment]
Por alguna razón al clickar en Alter trigger en el trigger creado me aparece vacío, pero dice crearse correctamente.

**Comment by profeIAP** [comment]
La edición (en general, da igual que sean tablas, vistas o triggers) es francamente mejorable en SQLiteman.

Personalmente suelo optar por:
1. eliminar el trigger (opción que está junto a la que mencionas)
1. volver a lanzar el script de creación

No  obstante tu trigger está en su sitio

![image](https://cloud.githubusercontent.com/assets/16881846/25963536/ec421c8c-3681-11e7-9837-36545da5429f.png)

**Comment by YellowZaki** [comment]
Sí, lo volví a borrar y crear varias veces y seguía igual.

**Comment by profeIAP** [comment]
👍
