### ISSUE TITLE
Crear método Denuncia::recuperar($id)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#496]
Crear el método indicado (similar al desarrollado en #434) que, dado un identificador único `$id' de una DENUNCIA :

1. [Obtenga de la tabla Denuncias de la BD](https://github.com/profeIAP/retados/blob/d0fcd62cf83b741508d2747930318f870839dc98/controller/Grupo.php#L93-L94) la entrada con el campo DENUNCIAS.ID= $id
1. [Utilizando el constructor de la clase](https://github.com/profeIAP/retados/blob/d0fcd62cf83b741508d2747930318f870839dc98/controller/Confirmacion.php#L85) Denuncia ( #495) y los datos recuperados, devuelva un objeto de tipo Denuncia.

**Comment by Carjosop** [comment]
Rapidito

**Comment by Carjosop** [comment]
De buen rollo

**Comment by profeIAP** [comment]
Perdonalos Fran porque no saben lo que dicen (o sí)

El problema es que les corre algo de prisa contar con esta tarea para poder implementar otras cosas.

Entendemos que estás con la...
![](http://loscedros.es/wp-content/uploads/2015/12/placa-L.png)
pero procura echarte al carril derecho para no enlentecer al resto de "conductores" ;)

**Comment by FcoHumanessab** [comment]
No me importa coger otra tarea.

**Comment by profeIAP** [comment]
Muchas gracias Fran, sabíamos que no tendrías inconveniente.
Como te he comentado en clase necesitamos que el "tráfico" fluya y, como estáis empezando y nos sois "diestros" (todavía) se os puede considerar

![image](https://user-images.githubusercontent.com/16881846/37211930-d69a48fe-23ad-11e8-8d1d-b507b96950f6.png)

**Comment by profeIAP** [comment]
Poco a poco, dentro de nada iréis como un 

![image](https://user-images.githubusercontent.com/16881846/37211983-0272b68c-23ae-11e8-8f9a-2b8e3c3cf2d5.png)

**Comment by profeIAP** [comment]
No está nada mal María pero sospecho que, como es normal (por estar empezando), te has liado un poco:
1. No existe el método `recuperar(...)` que hemos solicitado.
1. Se ha cambiado (y no debería ser así), el método `cargar(...)` que teníamos
Tómalo con calma... pronto empezarás a cogerle el truco, traquila.

**Comment by profeIAP** [comment]
Fantástico María, que buen trabajo.
Gracias

![image](https://user-images.githubusercontent.com/16881846/39259930-1e41106e-48b8-11e8-9d30-cccee2c0c238.png)
