### ISSUE TITLE
Crear método POST:preguntas/guardar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#5]
Crear un método que permita almancenar (insertar o actualizar) en la BD los datos, introducidos por el usuario, de una PREGUNTA.

Su implementación:

1. pedirá a Utilidades::getDatosFormulario() la informacińo enviada por el formulario
1. delegará en la tarea #16 almacenar la PREGUNTA en la BD
1. redireccionará a /preguntas una vez finalizado el proceso anterior

**Comment by profeIAP** [comment]
@julioosos te defino con más detalle el proceso que debes seguir.
He estado tentado a bajar el nivel de dificultad de la tarea por lo que puedes considerarlo un "regalo" 😏
Procura acabarla lo antes posible y así centrarte en la tarea #4 que tienes "reservada"

**Comment by julioosos** [comment]
Creo que ya está

**Comment by profeIAP** [comment]
Pues ni veo el commit ni lo que está implementado parece funcionar como debería (no se cumplen los puntos 2 y 3 que aparecen en la definición de esta tarea)

¿Es posible que no hayas hecho un push al repositorio de código?

**Comment by julioosos** [comment]
Podría ser mañana lo confirmo

**Comment by julioosos** [comment]
Ya está acabado

**Comment by profeIAP** [comment]
Perfecto Julio, gracias
