### ISSUE TITLE
Crear método Denuncia.getPregunta()

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#515]
Que devuelva el objeto PREGUNTA correspondiente a la PREGUNTA que ha sido denunciada, para ello debes:

1. Obtener el ID de dicha PREGUNTA (gracias al método Denuncia->getIdPregunta() definido en la tarea #510)
1. Devolver el resultado de invocar a Pregunta::recuperar(...) (tarea #514) con el ID obtenido en el paso anterior

**Comment by profeIAP** [comment]
Se añade test y comentarios al commit

**Comment by german4cda** [comment]
esta bien?

**Comment by profeIAP** [comment]
Como no parece que hayas subido algo nuevo (no hay commits posteriores al último que subiste), puedes comprobarlo tú mismo lanzando el test y mirando qué te he puesto en el comentario.

**Comment by profeIAP** [comment]
Fantástico Fran, buen trabajo.
Gracias
