### ISSUE TITLE
Corregir el menú principal en view/pregunta.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#52]
Se ha detectado un problema con el menú principal que debe ser subsanado

![captura de pantalla de 2017-04-06 14 05 41](https://cloud.githubusercontent.com/assets/16881846/24754808/25fbf774-1ad8-11e7-80f1-4708dd6f3340.png)

**Comment by Mahc99** [comment]
Finalizada.

**Comment by profeIAP** [comment]
Y muy bien finalizada que está... gracias Migue
