### ISSUE TITLE
Añadir campo PREGUNTAS.PRIVADA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#520]
Añadir a la BD el campo solicitado asumiendo, como valor por defecto, el 0

**Comment by profeIAP** [comment]
Sé que es un lío, pero observa que se ha perdido el campo `BLOQUEADA` en la BD

![image](https://user-images.githubusercontent.com/16881846/38427174-cf5d97e6-39b8-11e8-9f9c-d1699a9a4b77.png)

**Comment by adrivel** [comment]
Sí, me di cuenta que en la db no estaba el campo de bloqueada. Seguramente
fue porque mi base de datos no estaba actualizada, así que el próximo día
lo agrego.

**Comment by profeIAP** [comment]
Genial, muchas gracias "monstruo".

Sabes que tengo puestas muchas "esperanzas" en ti, tengo ganas de que termines de acostumbrarte a la metodología de trabajo que estamos siguiendo en este proyecto, nos vamos a divertir 👍

**Comment by profeIAP** [comment]
Ahora sí, perfecto Adrián
Buen trabajo, gracias
