### ISSUE TITLE
Crear método Pregunta::eliminarRespuestas($idPregunta)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#53]
Crear método **privado** que elimine TODAS las RESPUESTAS de la PREGUNTA cuyo ID se proporciona como parámetro de entrada

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Casi salvo que la implementación que has hecho está borrando realmente la PREGUNTA cuyo ID indicas (en lugar de las RESPUESTAS asociadas)

**Comment by carlosaj98** [comment]
Creo que ya la he arreglado

**Comment by profeIAP** [comment]
@YellowZaki, necesito que me expliques por qué has implementado una tarea de @carlosaj98 🤔

**Comment by profeIAP** [comment]
Ha quedado aclarado... Alberto confundió el número de tarea al hacer el commit y por éso ha aparecido aquí 😏

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Disiento, te dejo comentario sobre el fragmento de código que sobra.

Agradecería que confirmases que te ha saltado algún tipo de notificación por email (para seguir usando dicha forma de destacar los problemas que vaya detectando)

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Ahora sí, muy buen trabajo.
Tras observar la mejora en tu rendimiento, estoy por "exiliarte" de forma permanente 😏
