### ISSUE TITLE
Implementar método GET:/preguntas/confirmar/:hash

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#530]
Sustituir la implementación actual del método (tarea #528) por una llamada al método `Denuncia::rechazar($hash)` (tarea #534 )

**Comment by mariarodra** [comment]
![captura de pantalla de 2018-04-11 10 21 55](https://user-images.githubusercontent.com/34505679/38605304-2e7b1baa-3d73-11e8-8b71-dfead59e89f9.png)

**Comment by profeIAP** [comment]
Debes usar _git_ para subir los cambios y que todos podamos disfrutar de la funcionalidad que estás implementando :)

**Comment by mariarodra** [comment]
![captura de pantalla de 2018-04-13 11 23 40](https://user-images.githubusercontent.com/34505679/38727429-45b2b9a4-3f0d-11e8-8a2f-1aa80e0f2934.png)

**Comment by profeIAP** [comment]
Espectacular María, funciona perfectamente.
Muy buen trabajo, puedes sentirte orgullosa 👍
