### ISSUE TITLE
Implementar método GET:/preguntas/repudiar/:hash

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#535]
Sustituir la implementación actual (#527) del método por una llamada al método `Denuncia::aceptar($hash)` (tarea #529)

**Comment by Carjosop** [comment]
Estat Català

**Comment by profeIAP** [comment]
Teniendo en cuenta que:

1. @benjigar tenía actualmente asignadas 3 tareas (claro abuso a las normas más elementales de convivencia)
1. En esta tarea no ha realizado ninguna acción.

Considero, en base a la legislación vigente (en esta nuestra comunidad), correcto y aceptable que se apropie _debidamente_ de la tarea :)

**Comment by profeIAP** [comment]
Perfecto Marta, muy buen trabajo, gracias.
