### ISSUE TITLE
Crear método Pregunta::bloquear($id)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#538]
Cuyo objetivo será anotar un 1 en el campo `PREGUNTA.BLOQUEADA` de la PREGUNTA cuyo ID coincida con el indicado por `$id`.

Para ello:

1. generará un vector con los valores:
   + "ID" el contenido de la variable `$id` y
   + "BLOQUEADA" que tendrá por defecto el valor constante 1
1. utilice `AccesoDatos::guardar(...)` para anotar en la tabla PREGUNTAS los valores del vector anterior.

**Comment by profeIAP** [comment]
Tienes un [ejemplo parecido aquí](https://github.com/profeIAP/retados/blob/f80d9e815a771354bbdb60a468ad2a607b3e81e2/controller/Tema.php#L81-L88)

**Comment by profeIAP** [comment]
Añado comentario en el commit

**Comment by Rgm13** [comment]
A veces no se me cierra si cierro 2 a la vez.

**Comment by profeIAP** [comment]
Para que lo haga, tienes que poner el "Close #NNN" en líneas independientes (con retornos de carro)

![peek 05-04-2018 18-12](https://user-images.githubusercontent.com/16881846/38378101-fcf6d954-38fc-11e8-88e2-a03922b48fdf.gif)

**Comment by profeIAP** [comment]
Funciona perfectamente, doy por finalizada la tarea y elimino la penalización tras comprobar que se debía a no haber cerrado la tarea ~correctamente~ 😏
