### ISSUE TITLE
Destacar preguntas bloqueadas mostrando un icono en el enunciado

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#559]
Con una implementación similar a la tarea #558, deberás añadir el icono de la tarea #557 tras el texto del enunciado de la PREGUNTA si (y sólo sí) está bloqueada (deberás [usar condicionales](https://github.com/profeIAP/retados/blob/bb0c6f457bd4df3dc53993d6508134991f0e9535/view/preguntas.php#L12-L14), más detalles y/o ejemmplo en la tarea #558)

**Comment by profeIAP** [comment]
Quito la asignación a @adrivel por estar ya la tarea asignada previamente a @Rgm13.

Adri, sé que eres nuevo y debería estar especificaco en algún sitio que sólo pueden cogerse tareas que estén "libres" (sin tener ningún compañero asignado como responsable de ella) 😉

**Comment by adrivel** [comment]
Uh, no sabía. Sorry!

**Comment by profeIAP** [comment]
No te preocupes Adri, estamos en fase de "formación"... pa'lo que pago tampoco puedo exigir mucho 😂

Eso sí, cuando contestéis desde el móvil, eliminad el mensaje original (sólo debéis dejar vuestra respuesta), para evitar que aparezca "basurilla" en el hilo de la tarea

![image](https://user-images.githubusercontent.com/16881846/38431568-f01219c4-39c4-11e8-8663-6e29b3639e3b.png)

**Comment by profeIAP** [comment]
Has debido confundirte de tarea Gloria: en esta se pide que se muestre un ICONO junto al texto de las preguntas bloqueadas y lo que, casi has implementado, es cambiar el color del texto.

**Comment by profeIAP** [comment]
Esta tarea sigue sin ser la correcta, vuelves a confundirte con la #558

**Comment by profeIAP** [comment]
Aquí tienes [cómo puedes hacerlo](https://tympanus.net/codrops/css_reference/after/)

**Comment by profeIAP** [comment]
¡Qué guay! Muchas gracias Gloria

![flameshot-2018 05 03 11 07](https://user-images.githubusercontent.com/16881846/39568356-7a5539d0-4eb1-11e8-9d72-c8b51714ee46.png)
