### ISSUE TITLE
Añadir parámetros Pregunta::guardarRepuestas($idPregunta, $respuestaCorrecta, ...)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#56]
Añadir parámetros:
+ **$idPregunta** 
+ **$respuestaCorrecta**

al método, de modo que quede como Pregunta::guardarRepuestas($idPregunta, $respuestaCorrecta, $respuestas) en el que:
1. **$idPregunta** indicará la PREGUNTA a la que pertenecen las respuestas.
1. **$respuestaCorrecta** indicará la _posición_ que ocupa (de las N RESPUESTAS recibidas en _$respuestas_) la RESPUESTA acertada

**Comment by Mahc99** [comment]
Terminada

**Comment by profeIAP** [comment]
Migue, has cambiado la invocación (que era necesario) pero no la definición del método (que era lo que realmente habíamos pedido)

**Comment by Mahc99** [comment]
Ahora si.

**Comment by profeIAP** [comment]
Muchísimo mejor pero, nuevamente, siento tener que disentir: has implementado un Pregunta::guardarRepuestas(**...,** $idPregunta, $respuestaCorrecta) cuando se solicitaba un Pregunta::guardarRepuestas($idPregunta, $respuestaCorrecta**,...** )

Puede parecer lo mismo... pero no lo es 😏

**Comment by Mahc99** [comment]
Corregido y espero que terminado (?)

**Comment by profeIAP** [comment]
Ahora sí, gracias Migue
