### ISSUE TITLE
Añadir botón "Solicitar revisión"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#561]
Añadir botón a `view/pregunta.php` a los actualmente existentes

![image](https://user-images.githubusercontent.com/16881846/38429242-2b898156-39be-11e8-8dba-45900d57a21e.png)
con:

1. el texto "Solicitar revisión"
1. un color "anaranjado" 
1. usar /preguntas/revisar como url

**Comment by profeIAP** [comment]
Está bastante bien, pero has usado una versión antigua de view/pregunta.php y se te ha colado el switch que incluyó @Rgm13 (amén de perder los cambios que han hecho otros compañeros como @juankagb00)
 
![image](https://user-images.githubusercontent.com/16881846/38615200-1eb571bc-3d90-11e8-8c95-5af9bb52bd90.png)

**Comment by profeIAP** [comment]
Necesito que "juegues" con el espacio que ocupa cada botón para que no se solapen entre si

![image](https://user-images.githubusercontent.com/16881846/38685720-d74fad22-3e72-11e8-8ac2-a3dc04aa90be.png)

**Comment by gloocc8** [comment]
Por esto no me habrás puesto otro abuso no ? 😱😱😱 , Por que está bien
jaja 😬😭
