### ISSUE TITLE
Modificar método Pregunta::cargar($id)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#59]
Ampliar método que permite cargar una PREGUNTA (cuyo $id se proporciona como parámetro de entrada) para que incluya las RESPUESTAS asociadas (invocando a _Respuesta::listar()_ )

**Comment by flobato322** [comment]
En lo último que me queda no me funciona he puesto $p["Respuestas"]=$r lo que me dijiste para que pregunta dé las respuestas y no me funciona 👎

**Comment by profeIAP** [comment]
Pues algo se te debe haber escapado, Fran.

Como tengo interferencias con otros lenguajes de programación, acabo de realizar una prueba para confirmar que es un método correcto para añadir entradas a un array en PHP.

Tendremos que mirar los logs para ver qué está fallando 👍

**Comment by flobato322** [comment]
Terminada

**Comment by profeIAP** [comment]
Fran, te incluyo un comentario que necesito que tengas en cuenta para dar por cerrada la tarea.

**Comment by flobato322** [comment]
Ya la he terminado

**Comment by profeIAP** [comment]
Sí señor... funciona perfectamente, ¡enhorabuena!
