### ISSUE TITLE
Crear método Revision::rechazar($hash)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#592]
Crear el método solicitado que permita descartar una REVISION solicitada por un ALUMNO.

Para ello:

1. Invocará al método `Revision::finalizarConfirmacion(..)` (#590) con el hash recibido como parámetro de entrada y anotará en `$id` el resultado que devuelve.
1. Delegará en `Pregunta::bloquear(..)` el bloquear la PREGUNTA cuya REVISION ha sido rechazada.
1. Notificará que la REVISION ha sido rechazada invocando al método de la tarea #591

**Comment by Ezki14** [comment]
https://github.com/profeIAP/retados/commit/a5de80f7d54b8f781f1366b36e782742df1cc7fc

**Comment by profeIAP** [comment]
No existe el método solicitado

**Comment by profeIAP** [comment]
Perfecto gracias Ezki
