### ISSUE TITLE
Mostrar opciones de filtrado sólo al tutor del grupo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#599]
Una vez incluida la opción de filtrado en la tarea #598, añadir condición a `view/preguntas.php` para que sólo aparezca si el USUARIO logado es el propietario del GRUPO.

Se etiqueta como _fácil_ por ser una implementación idéntica a la realizada en la tarea #555

**Comment by mariarodra** [comment]
![Uploading Captura de pantalla de 2018-06-06 10:19:50.png…]()

**Comment by mariarodra** [comment]
![Uploading Captura de pantalla de 2018-06-06 10:19:50.png…](captura)

**Comment by profeIAP** [comment]
María, la implementación está perfecta pero recuerda que debes subir los cambios al repositorio utilizando el comando GIT (en lugar de adjuntar capturas de pantalla 😅)

**Comment by profeIAP** [comment]
Funciona perfectamente salvo por un par de detalles que se te han escapado y te he comentado sobre el propio commit.

Buen trabajo, María

**Comment by mariarodra** [comment]
Ya lo has arreglado maestro
