### ISSUE TITLE
Modificar método Pregunta::sortear()

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#60]
Ampliar el método que permite elegir al azar varias  PREGUNTAS para que incluya las RESPUESTAS asociadas (invocando a Respuesta::sortear() ) a dichas PREGUNTAS de forma aleatoria.

**Comment by profeIAP** [comment]
Cambio nivel de dificultad tras hablar con Patri y evaluar el objetivo con más detalle

**Comment by Patriexd** [comment]
@profeIAP tienes que mirarlo porque no encontramos el error

**Comment by Patriexd** [comment]
por cierto "accidentalmente" al subir los cambios, preguntas no aparece en la barra para hacer click, pero si le das desde la barra del enlace si que aparece. Es decir que estar está, pero no aparece arriba

**Comment by profeIAP** [comment]
Como quedó aclarado en clase se trata del resultado de haber implementado la tarea #75

**Comment by Patriexd** [comment]
entonces, ¿tengo que esperar a que acabe la tarea #75 ?

**Comment by profeIAP** [comment]
@Patriexd esta tarea empieza a ser crucial y está en el límite del tiempo.
Dedícale toda tu atención el lunes pues amenazo con terminarla a más tardar el miércoles.
**NOTA:** otra posibilidad sería degradarla a "normal" y dejar que la acabe yo... tú decides 😏

**Comment by profeIAP** [comment]
Fantástico Patri, funciona perfectamente
¡Gracias!
