### ISSUE TITLE
Corregir el botón Cancelar de view/pregunta.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#61]
Evitar que al pulsar **el botón cancelar** del formulario de edición de una pregunta se produzca el siguiente error.

![image](https://cloud.githubusercontent.com/assets/16881846/25188730/526c348c-2527-11e7-996b-c4b86e9db139.png)

**NOTA:** deberá invocarse un GET:/preguntas

**Comment by Mahc99** [comment]
Terminada

**Comment by profeIAP** [comment]
Fantástico, gracias Migue
