### ISSUE TITLE
Crear SQL para obtener las etiquetas sin usar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#63]
Crear SQL que devuelva el campo _TEXTO_ de todas las entradas con "contador" 0 obtenidas de lanzar la SQL de la tarea #47 

Esta SQL deberá ser utilizada por @YellowZaki en su tarea #49 

Se etiqueta como _normal_ (en lugar de _reto_) por implicar (única y exclusivamente) un where de contador=0 y no tener que gestionar ningún tipo de relación entre tablas.

**Comment by julioosos** [comment]
No te olvides de hacer la tarea de @carlosaj98 puesto k esta bloqueando el trabajo de dos compañeros

**Comment by julioosos** [comment]
tarea #47

**Comment by profeIAP** [comment]
Gracias por recordármelo Julio pero he de recordarte que la ortografía debe ser "mimada" por esta vía 😏

**Comment by profeIAP** [comment]
Me lo has enseñado en clase pero no has subido la sql (utiliza la carpeta model/scripts)

**Comment by manu21499** [comment]
@profeIAP ya esta acabada , estoy esperando a que el proyecto funcione

**Comment by profeIAP** [comment]
Pues en cuanto puedas/quieras... sube la SQL que ya funciona bien 👍

**Comment by manu21499** [comment]
@profeIAP ya esta subida lo que pasa que esta implementada como tarea#78 pero es la tarea #63

**Comment by profeIAP** [comment]
La que has liado, la buena noticia es que @YellowZaki [podrá utilizar tu SQL](https://github.com/profeIAP/retados/blob/41f2b64ee19a075806f2fb3a1b98cd516f6a5bf7/model/scripts/sql_etiquetasSinUsar.sql) para terminar su tarea.
Gracias Manu
