### ISSUE TITLE
Marcar la respuesta correcta en view/pregunta.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#64]
Actualmente todos las respuestas aparecen como falsas (esté indicada o no en el BD qué respuesta es la correcta)

Utilizar [el operador ternario en Twig](http://stackoverflow.com/a/11820359) (una forma abreviada de escribir una condicional IF) para [asignar el atributo _checked_](http://stackoverflow.com/a/5592372) a la respuesta que tenga un 1 en el campo RESPUESTA.CORRECTA

**Comment by julioosos** [comment]
Tarea finalizada.

**Comment by profeIAP** [comment]
Simplemente espectacular, qué falta nos hacía
Gracias Julio
