### ISSUE TITLE
Crear vista view/importarTema.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#640]
Que permita al USUARIO indicar en qué GRUPO (y con qué nombre) desea importar el TEMA que le han compartido.

Con una disposición similar a la siguiente:

![image](https://user-images.githubusercontent.com/16881846/39935667-12026aa2-554a-11e8-9acb-e01b63931048.png)

siendo los nombres de los componentes del formulario:

+ **TEMA** para indicar el nombre que queremos que tenga el tema
+ **ID_GRUPO** para el identificador del GRUPO en el que queremos importar el tema.
+ **HASH** campo oculto en el que almacenaremos el hash que se nos proporcionará desde el controlador de la aplicación

Ten en cuenta que:

1. La url a la que debe enviarse el formulario será POST:`/comparticion/aceptar`
1. La entrada "Crear NUEVO GRUPO" debe tener un color diferente al resto de grupos (para que llame la atención) y tendrá como _valor_ un -1

**Comment by profeIAP** [comment]
No es [el mejor ejemplo del mundo](https://stackoverflow.com/questions/30816797/bootstrap-form-group-for-radio-buttons) pero debería servir

**Comment by SantiagoJiBe** [comment]
Tarea [corregida](https://semillerodeempresas.blogspot.com/2018/05/problemas-de-la-clase-en-nuestra-clase.html)

**Comment by profeIAP** [comment]
El código sigue siendo el que había antes de que hayamos estado un rato después de la clase modificando la vista ¿te acordaste de hacer el push?

**Comment by profeIAP** [comment]
Fantástico Santi, gran trabajo.
Gracias
