### ISSUE TITLE
Crear método POST:/comparticion/aceptar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#646]
Cuyo único objetivo sea [anotar en el log](https://github.com/profeIAP/retados/blob/f95d8c741a9cd5e06534986ec40c938340ee15ba/index.php#L137) "Debemos importar el TEMA que nos han compartido"

**Comment by profeIAP** [comment]
Añado comentario al commit

**Comment by profeIAP** [comment]
Se añade comentario al commit

**Comment by Joselulopez** [comment]
No se en que me he equivocado :1st_place_medal:

**Comment by profeIAP** [comment]
Añado comentario al commit para tratar de aclararte la duda 👍

**Comment by profeIAP** [comment]
Perfecto JoseLu, muy buen trabajo.
Disculpa el despiste con el commit 😅
