### ISSUE TITLE
Añadir botón para crear nuevas PREGUNTAS en view/preguntas.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#65]
Actualmente no existe ningún medio para crear nuevas preguntas.

Deberá incluirse un botón (con algún icono alusivo) que permita añadir nuevas entradas en la lista de PREGUNTAS.

El botón deberá invocar un GET:/preguntas/crear

**Comment by Patriexd** [comment]
¿De que color quieres el boton? Bueno, lo pongo azul o amarillo, gracias por la aportación xd

**Comment by Patriexd** [comment]
maybe... orange

**Comment by profeIAP** [comment]
Aquí puedes obtener los [iconos posibles](http://getbootstrap.com/components/)

**Comment by Patriexd** [comment]
![captura de pantalla de 2017-04-24 11 24 24](https://cloud.githubusercontent.com/assets/15888941/25330673/bf36f392-28e0-11e7-8b7e-dda14dde4054.png)

¿te gusta el textito y el color? @profeIAP

**Comment by profeIAP** [comment]
Me parece fantástico, Patri

Estoy deseando poder verlo en el repositorio pero recuerda que estás usando una versión peligrosamente antigua de view/preguntas.php 😅

**Comment by profeIAP** [comment]
Y el peligro se ha materializado en esta aberración 

![imagen](https://cloud.githubusercontent.com/assets/16881846/25528093/4b44346a-2c1c-11e7-8885-c15e54b593e8.png)

**Please,** no nos dejes la basura ahí 😏

**Comment by profeIAP** [comment]
Independientemente de tener que eliminar el "sobrante" (tras realizar una prospección, se ha observado que ha sido provocado por su intervención y no por la de su primo Julio como argumentaba inicialmente) se observa que el botón no invoca el _GET:/preguntas/crear_ solicitado en la descripción de esta tarea.
Desgraciadamente y, quedando poco, no podemos dar por finalizada esta tarea.
Ánimo

**Comment by profeIAP** [comment]
Fantástico Patri peeeerooo... ¿por qué no invoca el  GET:/preguntas/crear como se solicita en la tarea?
Te recomendaría mirar cómo están hechos [los "botones" en el formulario view/pregunta.php](https://github.com/profeIAP/retados/blob/43e3f0a69039246dfe792b4c31cb288eb948578d/view/pregunta.php#L82)

**Comment by Patriexd** [comment]
¿Que es lo que falla o falta?

**Comment by profeIAP** [comment]
Patri, ¿por qué no has subido los cambios que te he visto realizar esta mañana en el botón?
Espero explicación antes de optar por quedarme yo la tarea 😇

**Comment by profeIAP** [comment]
Fantástico Patri, la única "pena" que tengo es que queda algo para adentro el botón 😥
