### ISSUE TITLE
Mostrar vista view/malandrin-hash.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#659]
En caso de recibir una url sin "hash", [renderizar la vista](https://github.com/profeIAP/retados/blob/02f797a4d89c1de5017787c9613cffa0009b53f5/index.php#L325) implementada en la tarea #658 en lugar d[el echo actual](https://github.com/profeIAP/retados/blob/02f797a4d89c1de5017787c9613cffa0009b53f5/index.php#L116)

**Comment by profeIAP** [comment]
Lástima, añado comentarios al commit

**Comment by profeIAP** [comment]
Con las ganas que tengo de verlo funcionando como es debido y... tengo que volver a añadir comentarios en el commit

**Comment by Joselulopez** [comment]
No soy 100tifico jaja salu2.

**Comment by Joselulopez** [comment]
Soy 1000itar, y me109cito.

**Comment by profeIAP** [comment]
Anotaré que te gustan los jeroglíficos para escribir "a tu gusto" la descripción de la próxima tarea 😏

![image](https://user-images.githubusercontent.com/16881846/41674424-39a90cd8-74c0-11e8-862b-734f61f05b33.png)

No obstante, he de reconocer, que la tarea está perfecta.

¡Buen trabajo JoseLu!
