### ISSUE TITLE
Ubicar las ETIQUETAS de una PREGUNTA a la derecha del textArea

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#67]
Modificar _view/pregunta.php_ para cambiar la ubicación de las etiquetas de una pregunta de forma que queden como puede observarse en la imagen

![captura de pantalla de 2017-04-21 18-08-54](https://cloud.githubusercontent.com/assets/16881846/25286480/2fcad86e-26be-11e7-89a8-80adb4731ce5.jpg)

Se etiqueta la tarea como _reto_ pues se exigirá (tal y como puede verse en la imagen) que la caja que permite escribir nuevas etiquetas esté por encima de las etiquetas ya introducidas (las que aparecen abajo en azul)

**Comment by YellowZaki** [comment]
Corrigo el error de las etiquetas y pongo Vista y quito normal (porque se indica en la tarea que es reto)

**Comment by profeIAP** [comment]
Gracias por corregirlo... parece que el viernes tenía los dedos demasiado "gordos" 😅

**Comment by YellowZaki** [comment]
No me aparecen las etiquetas ya añadidas, solo las que se van añadiendo
![captura de pantalla de 2017-04-28 11 19 29](https://cloud.githubusercontent.com/assets/13599841/25522935/154ac6d8-2c05-11e7-8a7a-44e87061ee7f.png)

**Comment by profeIAP** [comment]
No te preocupes Alberto, es responsabilidad de la tarea #69 👍

Lo que sí agradecería es que:
1. Cambies el ancho de la caja de texto para que se adapte al 100% del espacio que tiene asignado (queda raro que vaya creciendo el número de etiquetas introducidas)
1. Alinees a la misma altura la etiqueta TAGS con PREGUNTA

**Comment by YellowZaki** [comment]
Creo que se debería quedar que aumente de tamaño la caja de texto cuando crece el número de etiquetas.
Además he intentado establecer una altura fija y cuando no caben más etiquetas, se salen fuera.

**Comment by profeIAP** [comment]
Es lógico pensar que la altura deberá ir creciendo en función de las necesidades pero, observa en el comentario que te dejé, que solicito fijar la **ANCHURA** al 100% del espacio que tiene disponible.

Una **duda**, ¿es posible establecer una altura mínima (aunque luego vaya creciendo)? La idea es tener un espacio lo suficientemente grande como que sea de utilidad en el 90% de los casos aunque, en caso de necesidad (más etiquetas de las deseables) vaya creciendo?

No sé si he sabido transmitir la idea (la hora no es la más apropiada para tener sangre en el cerebro) pero, si no es así, lo hablamos en tu próxima "cita previa" que he visto que tienes reservada 😉

**Comment by YellowZaki** [comment]
Ya está hecho. ¿Cierro la tarea o espero a que se agreguen las etiquetas de debajo de la caja de texto para ponerlas en su lugar?

**Comment by profeIAP** [comment]
Aunque relacionada, puedes cerrarla sin miedo tras haber logrado el objetivo de la tarea.
Es más... te la cierro yo directamente 👍
