### ISSUE TITLE
Destacar el encabezado de view/preguntas.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#68]
Modificar el encabezado de la tabla (que permite mostrar la lista de preguntas existentes) de modo que permita destacarla respecto al resto de información que se muestra en la página.

**Comment by julioosos** [comment]
Terminada.

**Comment by profeIAP** [comment]
Julio, puestos a poner "tonos azulitos" ¿qué te parece utilizar el mismo que el del encabezado en lugar de añadir otro tono más a la "paleta de colores"? ;)

![imagen](https://cloud.githubusercontent.com/assets/16881846/25527804/c17716cc-2c1a-11e7-83ce-cd62d5fe5d3f.png)

**Comment by julioosos** [comment]
Terminada

**Comment by profeIAP** [comment]
Perfecto Julio, muchas gracias.
