### ISSUE TITLE
Indicar correctamente la ventana activa

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#70]
Independientemente de la página en la que te encuentres, siempre aparece _activo_ en el menú superior la opción _Acerca de_

![image](https://cloud.githubusercontent.com/assets/16881846/25495552/cebb28a2-2b7d-11e7-97a4-21bfa2bcfce7.png)

Se recomienda estudiar [cómo utilizábamos el _tabActivo_](https://github.com/profeIAP/panelDeControl/blob/784f449c3b2ff9de754ff96b3aec69c646d88573/view/about.php#L3) en el proyecto del año pasado para indicar la opción de menú a "iluminar".

**Comment by Patriexd** [comment]
@profeIAP, ¿ este reto es muy reto?

**Comment by josufg** [comment]
@Patriexd Yo no supe exactamente lo que pasaba con el tabActivo jajaja

**Comment by profeIAP** [comment]
Bastante reto... se podría decir que resulta hasta insano 😅

**Comment by profeIAP** [comment]
Ha quedado perfecto, muchísimas gracias Alberto ¡Gran trabajo!
