### ISSUE TITLE
Alinear a la izquierda la etiqueta Pregunta

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#71]
Alinear correctamente la etiqueta del texto de una PREGUNTA

![image](https://cloud.githubusercontent.com/assets/16881846/25495666/3e5dd196-2b7e-11e7-8f2d-261e8f871b2a.png)

**Comment by carlosaj98** [comment]
Creo que ya la he terminado

**Comment by profeIAP** [comment]
Se puede dar por finalizada, gracias Carlos
