### ISSUE TITLE
Actualizar el logotipo del formulario de login

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#72]
Cambiar la imagen del formulario de login (GET:/login) para que muestre el nuevo icono desarrollado por @Patriexd en la tarea #27 

![image](https://cloud.githubusercontent.com/assets/16881846/25496103/07139dfe-2b80-11e7-90e4-5022e5202f3c.png)

**Comment by profeIAP** [comment]
Cambio a _fácil_ la tarea (la "inercia" me ha jugado una mala pasada y la había etiquetado mal 😅)

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Y ha quedado estupendamente, gracias Carlos
