### ISSUE TITLE
Mostrar opción "Mi perfil" sólo si hay un usuario registrado

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#73]
Actualmente aparece (por defecto) la opción _Mi Perfil_ en el menú de la aplicación.

![image](https://cloud.githubusercontent.com/assets/16881846/25496378/009c5a5a-2b81-11e7-980d-d04cfd6db4d8.png)

En base a [la solución de Panel de Control](https://github.com/profeIAP/panelDeControl/blob/728f3fd7f8150aa1a809db2dc864f1f8bce9a84b/view/layout.php#L91):

+ Mostrar _Login_ (GET:/login) si no hay usuario logado en el sistema
+ Mostrar _Mi Perfil_ en caso contrario

**Comment by profeIAP** [comment]
Desgraciadamente, y como vimos en clase, aparece la opción _Logout_ en lugar del menú de opciones que teníamos inicialmente

![image](https://cloud.githubusercontent.com/assets/16881846/25663003/cac68190-3016-11e7-9556-196c10d16101.png)

**Comment by flobato322** [comment]
No me funciona Mi perfil echale un vistazo aver que le pasa:(

**Comment by profeIAP** [comment]
Gracias por recordármelo, intentaré echarle un vistazo... pero corrige la falta de ortografía que me están doliendo todavía los ojos 😬

**Comment by profeIAP** [comment]
Tras corregir la incidencia, podemos dar por cerrada tu tarea (no era cosa tuya)
Gracias Fran, un gran trabajo
