### ISSUE TITLE
Actualizar enlace Mi Perfil > Mis preguntas

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#75]
Modificar el enlace de la opción mostradada

![image](https://cloud.githubusercontent.com/assets/16881846/25496684/24f88f80-2b82-11e7-974e-e6d1a37a5869.png)

para que invoque GET:/preguntas.

Aprovechar la ocasión para **eliminar** las preguntas del menú principal

![image](https://cloud.githubusercontent.com/assets/16881846/25496753/6d2cbbfa-2b82-11e7-8db5-54cf13f1b047.png)

**Comment by josufg** [comment]
@profeIAP Finiquitada en 30 segundos jajaja

**Comment by profeIAP** [comment]
Perfecto Josué, gracias
