### ISSUE TITLE
Mostrar opciones rápidas en la pantalla de inicio

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#76]
Se debe permitir al usuario acceder rápidamente desde la pantalla de inicio (view/inicio.php) a las acciones más habituales de la web

![](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fd2zav2bjdlctd5.cloudfront.net%2Fuploads%2F2016%2F10%2Ffree-portfolio-html5-bootstrap-template.jpg&f=1)

Entre las opciones previsibles se encuentran las siguientes opciones (aunque están por confirmar y se irán definiendo conforme vaya evolucionando el proyecto)

+ Entrenar (respondiendo PREGUNTAS)
+ Concursar (en cualquier CUESTIONARIO generado por el PROFESOR de la ASIGNATURA)
+ Retar (a algún compañero de clase a ver quién falla antes, contesta más preguntas bien, ...)
+ Crear (PREGUNTAS para que otros compañeros las respondan)
+ Revisar (las estadísticas de sus PREGUNTAS)
+ ...

Para ello lo mejor es utilizar alguno de los siguientes plugins con imágenes (o colores) que permitan al USUARIO identificar rápidamente (e idealmente sin tener que leer) las opciones disponibles:
1. Responsive [portfolio](http://www.jqueryscript.net/layout/jQuery-Plugin-To-Create-A-Responsive-Portfolio-Website-Portfolio.html)
1. [jPortilio](http://www.jqueryscript.net/other/jQuery-Plugin-To-Filter-Responsive-Grid-Of-Items-jPortilio.html)
1. [Win8](http://www.jqueryscript.net/animation/Expanding-Overlay-Effect-with-jQuery-CSS3.html) portfolio

**NOTA:** el objetivo es seleccionar una de las opciones propuestas (si encuentras otra que te guste más será bienvenida) y utilizarla en la web. Sería **de especial interés** comentar qué opción se implementará **antes de hacerlo** (para evitar trabajo innecesario y alcanzar una propuesta que agrade a la mayoría del equipo)

No te preocupes:
1. por las imágenes y/o los colores (sólo procura que resulten excesivamente diferentes a los actualmente existentes)
1. cubrir todas las opciones posibles (incluye algunas de las de arriba, ya lo iremos afinando)

**Comment by Patriexd** [comment]
Recuerda mirar porqué no funciona esta tarea @profeIAP :D

**Comment by profeIAP** [comment]
Estaba prácticamente bien pero había un problemas con la librería jPortilio (debe cargarse antes que el _body_ para que funcione)

Sólo te falta "colorerarlo" 😏

**Comment by profeIAP** [comment]
Oki doki
