### ISSUE TITLE
Incluir opción Registro/Entrar en el menú principal

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#77]
Sustituir la opción _Log In_ del menú principal por _Registrarse / Entrar_ de modo que invoquen a:
1. **Entrar** (GET:/login)
1. **Registrarse** (GET:/signup)

**Comment by julioosos** [comment]
necesidad de que subas la dificultad anormal de momento y necesito instrucciones sobre como ponerlo en una sola barra

**Comment by profeIAP** [comment]
Si lo resuelvo yo, me quedo los puntos para mi ¿no te parece? 😏
Te dejo elegir: 
+ subimos la "apuesta" a normal y lo arreglas tú
+ lo dejas como está y ya me encargo yo del resto

**Comment by julioosos** [comment]
Lo que uno empieza, uno acaba subela 😎

**Comment by julioosos** [comment]
No obstante no estaría mal alguna orientación sobre como hacerlo

**Comment by profeIAP** [comment]
Ole ahí los "becarios" buenos... esa es la actitud, di que sí 👍

**Comment by julioosos** [comment]
Terminada según yo.

**Comment by profeIAP** [comment]
Al final considero que no es tan mala idea la de crear una tarea para que sea otro el que se encargue de alinear correctamente el contenido de la opción de menú.

Si pondré una "condición": 
1. haz que llame algo más la atención la barra separadora (actualmente apenas se aprecia)
1. pon algún espacio a ambos lados de la barra para desctacarla aún más.

Gracias Julio

**Comment by julioosos** [comment]
Valee

**Comment by julioosos** [comment]
Terminada.

**Comment by julioosos** [comment]
Terminada.

**Comment by profeIAP** [comment]
Aunque entiendo que ya debes estar cansado de esta tarea, sigo viendo demasiado juntos los textos ¿has utilizado realmente los códigos html que te he indicado? (en el commit sólo se observan espacios adicionales pero no dichos códigos y el resultado es prácticamente lo que ya teníamos)

![image](https://cloud.githubusercontent.com/assets/16881846/25957881/959d71cc-366f-11e7-82f7-5d93aa71a0cc.png)

**Comment by profeIAP** [comment]
Julio, buscando por qué se han perdido las preguntas creadas por @carlosaj98 (en la tarea #90) observo que has subido una versión antigua de _model/retados.db_

Agradecería restaurases los datos perdidos.

Es tan sencillo como:
1. lanzar las consultas que aparecen en el fichero que subió Carlos en su tarea 90
1. incluir _model/retados.db_ en el commit de esta tarea

Exigiremos que se restaure el status original para dar por cerrada tu tarea 😏

**Comment by profeIAP** [comment]
Aunque alguien se ha vuelto a cargar los datos (ya lo encontraremos y exigiremos que lo arregle) observo que dejaste perfectamente cerrado el tema.

Buen trabajo Julio y gracias.

**Comment by profeIAP** [comment]
Al final, y contra todo pronóstico, ha sido el propio @carlosaj98 quien se lo ha cargado 😳 [en el commit siguiente al tuyo](https://github.com/profeIAP/retados/commit/511067e4d2e86a4760f2de8b9c61ab0050e16f99)

**Comment by julioosos** [comment]
Propio de @carlosaj98 eso de cargarse lo ya arreglado
