### ISSUE TITLE
Crear método GET:/signup/

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#78]
Crear **grupo** en index.php (similar al que [tenemos para /login](https://github.com/profeIAP/retados/blob/712aa39a391f35ffe7bbdd84d788b098f7443385/index.php#L260)) que redireccione a _view/signup.php_

**Comment by manu21499** [comment]
@profeIAP la tarea esta acabada , estoy esperando a que arreglen el proyecto para poder subirla

**Comment by profeIAP** [comment]
Arreglado está, súbela en cuanto puedas (y corrige las faltas de ortografía para darla por "bien cerrada" 😏)

**Comment by manu21499** [comment]
@profeIAP Aunque en el commit menciono la implementacion de la tarea #78, también subo la tarea #63

**Comment by profeIAP** [comment]
Perfecto Manu esta tarea, aunque algo "liada", también está bien.
Gran trabajo 👍
