### ISSUE TITLE
Crear vista alta USUARIO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#79]
Crear vista HTML que permita indicar los datos de un USUARIO siguiendo el siguiente modelo

![image](https://cloud.githubusercontent.com/assets/16881846/25667601/41b30dac-3024-11e7-93fe-0169e18af40a.png)

No es necesario que el formulario realice ninguna acción ni responda a ningún evento; sólo incluir los distintos elementos que aparecen en la imagen.

Se etiqueta como RETO por el tiempo que requerirá crear el formulario desde cero.

**NOTA:** para su elaboración:
+ se podrá utilizar el formulario de login (view/login.php)
+ se deberá incluir el logotipo del proyecto (en la parte superior o en alguno de los laterales de los campos que pueden observarse en el boceto de arriba)
+ puede utilizar como base cualquier plantilla de login para Bootstrap mientras los colores sean similares a los usados en el proyecto y/o no resulte excesivamente estridente

**Comment by Mahc99** [comment]
Terminada =P.

**Comment by profeIAP** [comment]
Me temo que necesita (como era de suponer) algún retoque para que termine de estar correctamente implementada.

De las **condiciones iniciales** echo de menos el logotipo del proyecto: sé que has usado la versión de Fran que lo ha "perdido" pero siempre puedes:
1. Tirar del histórico de cambios de login.php y coger una versión que tenga la imagen
1. Arreglarlo por tu cuenta (y de paso contarle a @flobato322 cómo se hace que "seguro" que te lo "agradece" 😏)

Agradecería:
1. incluyeses [el atributo _action_](https://github.com/profeIAP/retados/blob/1bab359a1e360789ded92d9b7cb03e194c06c436/view/login.php#L17) tal y como se observa en el ejemplo suministrado.
1. hagas apuntar dicho atributo a _POST:/signup_

**Comment by profeIAP** [comment]
Un par de apreciaciones adicionales, Migue.
Observa:
1. El campo pone Apellido**S**
1. Dicho campo ocupa el 75% del espacio (el de Nombre es algo inferior)

**Comment by Mahc99** [comment]
Pues ya estaría, o eso espero.

**Comment by profeIAP** [comment]
O eso sería de esperar... personalmente sigo esperando [que implementes la 2ª recomendación](https://github.com/profeIAP/retados/issues/79#issuecomment-300540832) 😏

**Comment by Mahc99** [comment]
No había entendido esa 2º recomendación. Ya he corregido y el campo apellidos ocupa el 75%.

**Comment by profeIAP** [comment]
Y ha quedado espectacular, gracias Migue

![image](https://cloud.githubusercontent.com/assets/16881846/26063016/f6451758-398c-11e7-8ede-50e7f95617fa.png)

**Comment by profeIAP** [comment]
Uuumm... está algo torcido en el portátil ¿no? 

![captura de pantalla de 2017-05-16 17 47 36](https://cloud.githubusercontent.com/assets/16881846/26115267/c9ebee4c-3a5f-11e7-9c88-daa75a6649f0.png)

**Comment by Mahc99** [comment]
Creo que ya lo he centrado.

**Comment by profeIAP** [comment]
Suena a chapu (usar el fluid y mezclar sm y md a la hora de intentar cuadrar las cosas) pero, a falta de probarlo en un portátil (que lo probaré y lo sabes 😏) lo voy a dar por bueno.

![imagen](https://cloud.githubusercontent.com/assets/16881846/26151703/3b83c09e-3b04-11e7-94a2-af6e61dd10fb.png)

Considero que costaba menos trabajo hacerlo bien desde cero (y no usar el fluid) que intentar "apañarlo" pero podría valer... de momento jeje
