### ISSUE TITLE
Crear vista listado PREGUNTAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#8]
Crear formulario HTML en el que se listarán las distintas PREGUNTAS almacenadas en el sistema.

![captura de pantalla de 2017-02-15 17-22-48](https://cloud.githubusercontent.com/assets/16881846/22983782/7f978444-f3a3-11e6-9f41-bde4f9e752d4.png)

El objetivo es simplemente incluir el listado, ni siquiera hace falta acceder a la BD para recuperar las PREGUNTAS que haya almacenadas (si lo necesitases puedes poner un par de ellas codificadas directamente en la vista)

Se etiqueta como RETO por el tiempo que requerirá crear el formulario desde cero.

**Comment by profeIAP** [comment]
Se edita el título de la tarea para facilitar su localización.

**Comment by julioosos** [comment]
creo k esta ya

**Comment by profeIAP** [comment]
Como "principio elemental" (que aplicaré a todos los comentarios que emita el equipo de desarrollo) no se admitirán faltas de ortografía ni usar el modo de escritura abreviado de los móviles. En caso de detectarse alguna incorrección, optaré por abrir la tarea hasta que sea subsanado, ¿os parece "razonable"? 🤔

**Comment by profeIAP** [comment]
Entiendo que no has podido probar el formulario pues @josufg aún no ha implementado la tarea #3 pero yo sí lo he hecho y observo que hay un par de problemas (echále un vistazo cuando puedas 😉)

![captura de pantalla de 2017-03-03 16-23-20](https://cloud.githubusercontent.com/assets/16881846/23556873/5b9623d8-002e-11e7-9cb9-35446538c4d6.png)

**Comment by julioosos** [comment]
Ya lo he terminado

**Comment by julioosos** [comment]
.
PD: Perdón se me había olvidado el punto.

**Comment by profeIAP** [comment]
Está infinitamente mejor, estás haciendo un gran trabajo Julio (gracias).

Sin embargo observa que **ninguno de los dos** botones utilizan la ruta correcta que debería ser:

1. **Borrado:** /preguntas/borrar?ID=3
1. **Edición:** /preguntas/editar?ID=3
![captura de pantalla de 2017-03-08 16-25-33](https://cloud.githubusercontent.com/assets/16881846/23710191/1fc537f8-041c-11e7-9a01-6c7955ec71f0.jpg)

Corrije esto y lo cerramos definitivamente 👍

**Comment by julioosos** [comment]
Ya está.

**Comment by profeIAP** [comment]
Aunque feo de dolor (ya lo arreglaremos) acepto la solución por funcional y válida.
Gracias Julio, muy buen trabajo.
