### ISSUE TITLE
Ubicar correctamente el botón de login.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#80]
Alinear a la derecha y cambiar su nombre por **Acceder** el botón de view/login.php
![image](https://cloud.githubusercontent.com/assets/16881846/25667862/1edcc2c2-3025-11e7-8862-4359a28d4dde.png)

**Comment by josufg** [comment]
@profeIAP Listo

**Comment by profeIAP** [comment]
Añado comentario a tu commit

**Comment by josufg** [comment]
@profeIAP En la implementación de la tarea #83 he insertado también esta pero se me ha olvidado comentarlo en el commit. La cierro tambien

**Comment by profeIAP** [comment]
Se te olvida mencionar las mejores... ¡Gran trabajo Josué!
