### ISSUE TITLE
Habilitar registro en login.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#81]
Añadir enlace

1. con texto **Registrarse**
1. con enlace GET:/signup

en el formulario view/login.php.

![image](https://cloud.githubusercontent.com/assets/16881846/25668140/11206ae8-3026-11e7-93d3-d5a8a1066519.png)

La idea es permitir a los usuarios darse de alta en el sistema si, al intentar entrar, descubren que todavía no tienen cuenta.

**Comment by profeIAP** [comment]
Desgraciadamente no está bien finalizada la tarea

![image](https://cloud.githubusercontent.com/assets/16881846/25709259/1df91f62-30e9-11e7-869f-02c93f98e2eb.png)

**Comment by profeIAP** [comment]
Normal que no te cuadre Jesús... te he dejado algunos comentarios sobre el código que has subido

**Comment by j1m1** [comment]
Voy a volver a subir la tarea con el arreglo del /signup
 Respecto a lo del botón y el enlace, no se pueden pegar más de lo que están. 
Alguien, supongo que el que ha añadido el logo, lo ha vuelto a mover.

**Comment by profeIAP** [comment]
Tienes razón, daremos por finalizada la tarea puesto que se observa (y @Mahc99 lo está sufriendo con su tarea #79) que el formulario está mal "maquetado" (sólo se usan col-sm-NN y no de forma coherente).

Demasiado que funciona bien.

Gracias Jesús
