### ISSUE TITLE
Permitir volver a la web desde login.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#82]
Añadir un enlace al icono del proyecto existente en view/login.php 

![image](https://cloud.githubusercontent.com/assets/16881846/25668278/9419d1b4-3026-11e7-94c7-28162527c5ee.png)

de modo que, al pinchar sobre él, nos devuelva a la página de inicio del proyecto (GET:/)

**Comment by profeIAP** [comment]
Añado comentario sobre el propio commit

**Comment by flobato322** [comment]
Creo que está ya bien

**Comment by profeIAP** [comment]
Desgraciadamente no se vé la imagen en el formulario.
Te dejo comentario sobre el propio código

**Comment by flobato322** [comment]
Terminada

**Comment by profeIAP** [comment]
Ha quedado espectacular, ¡Enhorabuen Fran!

**Comment by profeIAP** [comment]
Fran, te vuelvo a abrir la tarea tras observar que nos has metido "ruído" y, las carpetas **que borré en su momento**, han vuelto a aparecer

![image](https://cloud.githubusercontent.com/assets/16881846/25961624/2ee9be8e-367b-11e7-8094-6645efc21eb6.png)

**Comment by flobato322** [comment]
Ya lo he borrado pero al subirlo me sale everything up-to-date

**Comment by profeIAP** [comment]
Se debe a que no has utilizado un `git rm`

**Comment by flobato322** [comment]
Ya he subido el commit sin las carpetas

**Comment by profeIAP** [comment]
Me temo que no...

![image](https://cloud.githubusercontent.com/assets/16881846/26062902/9b2a8326-398c-11e7-8dd1-0879718090f5.png)

**Comment by profeIAP** [comment]
¡Por fiiiinnn!
Buen trabajo Fran, parece que has "vuelto" con fuerza 😉👍
