### ISSUE TITLE
Evitar mostrar login.php más de lo necesario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#83]
Modificar [el evento GET:/login](https://github.com/profeIAP/retados/blob/712aa39a391f35ffe7bbdd84d788b098f7443385/index.php#L262) para evitar que se muestre el formulario login.php [si el usuario ya está logado](https://github.com/profeIAP/retados/blob/712aa39a391f35ffe7bbdd84d788b098f7443385/controller/Login.php#L7) 

**NOTA:** Si el usuario ya estuviese logado, se redireccionaría a la página de inicio (GET:/) en lugar de renderizar view/login.php

**Comment by josufg** [comment]
@profeIAP Correcto

**Comment by josufg** [comment]
@profeIAP Listo. A la espera de que arreglen el estropicio

**Comment by profeIAP** [comment]
Ha quedado perfecto, muchas gracias Josué
**NOTA:** parece que estás en "racha" ¿no? 👍
