### ISSUE TITLE
Crear el método Pregunta::getRespuestaCorrecta($pregunta)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#84]
Crear el método indicado de modo que:

1. Recorra todas sus RESPUESTAS
1. Devuelva un número entero (0 index) indicando en qué posición se encuentra la respuesta acertada

A modo de ejemplo, de la siguiente PREGUNTA con sus RESPUESTAS, debería devolver un 2 (está en la posición 3 pero, como contamos desde cero devolverá 3-1=2)

![image](https://cloud.githubusercontent.com/assets/16881846/25753087/9423839a-31ba-11e7-8f6b-1a8c2dd76550.png)

**Comment by josufg** [comment]
Aunque me sale como usuario (aun no habia configurado mi usuario y email en este nuevo portatil) ya la he subido

**Comment by profeIAP** [comment]
Perfecto Josu, ha quedado genial, gracias.
