### ISSUE TITLE
Crear método Pregunta::anotarRespuestasCorrectas($preguntas)

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#86]
Crear el método indicado de modo que, dada una colección de PREGUNTAS ($preguntas) invoque, para cada una de las PREGUNTAS al método creado en la tarea #85 

El procedimiento a seguir será:
1. Crear un bucle para recorrer las distintas PREGUNTAS existentes en el parámetro de entrada $preguntas
1. Para cada PREGUNTA individual invoque a Pregunta::anotarRespuestaCorrecta() definido en la tarea #85 
1. Devuelva el resultado de haber procesado las PREGUNTAS

**Comment by Rafaelcraftero** [comment]
seguro que no tengo que modificar el método de la tarea #85 dado que lo único que cambia es que $pregunta esta en plural en la tarea #86 y creo que es un error tipográfico

**Comment by profeIAP** [comment]
No se trata de un error tipográfico, Rafael.
La definición es correcta y el objetivo, claro

**Comment by profeIAP** [comment]
Anoto sobre el propio commit

**Comment by profeIAP** [comment]
Comento sobre el propio commit

**Comment by profeIAP** [comment]
Incluyo comentario sobre el propio commit

**Comment by Rafaelcraftero** [comment]
Es completamente imposible que pueda probar los commits por lo que intento repasar el código muchas veces para no cargarme nada pero se me puede pasar algo.

**Comment by Rafaelcraftero** [comment]
pero en el commit no me has dicho nada, simplemente me has amenazado de muerte y has corregido la otra tarea que es la #106 no la #86

**Comment by profeIAP** [comment]
Los avisos no son amenazas, Rafael...
No obstante sigue sin funcionar, he dejado [comentario en el commit ](https://github.com/profeIAP/retados/commit/00de3aa987a440466366d31332c5aac5859fd0e7#diff-0aa9e5fba5cc1cf1681eb710f93edb17R81)

**Comment by profeIAP** [comment]
Ha costado pero la espera ha merecido la pena.
Enhorabuena 👍
