### ISSUE TITLE
Anotar en el JSON la RESPUESTA correcta de un CUESTIONARIO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#88]
Modificar la [generación del JSON](https://github.com/profeIAP/retados/commit/0b3730edba198fc61ff95521a9619356d06b0d29#diff-8b0a64afed77a473947677d1a8f7936fR15) para que muestre (en lugar del 0 que aparece en la línea de código indicada) el contenido de p.CORRECTA

**Comment by julioosos** [comment]
Terminada.

**Comment by profeIAP** [comment]
Fantástico Julio, ¡buen trabajo!

**Comment by julioosos** [comment]
A pesar de ser una fácil XD
