### ISSUE TITLE
Traducir jQuery Quick-Quiz al castellano

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#89]
Cambiar todos los mensajes (y botones) mostrados por la librería _jQuery Quick-Quiz_ de modo que aparezcan en "perfecto castellano"

![image](https://cloud.githubusercontent.com/assets/16881846/25755263/8fc79022-31c2-11e7-8d71-6d77bc609650.png)

Para ello deberás modificar las cadenas de texto ([como ésta](https://github.com/profeIAP/retados/blob/1dc7c092925f1e537b99325f3b63f2fc55a3615b/js/quiz.js#L186)) del fichero js/quiz.js

**Comment by julioosos** [comment]
Terminada.

**Comment by profeIAP** [comment]
Para ser un reto casi la has terminado Julio, muy buen trabajo.

Debes cuidar un poco las traducciones y no hacerlo "literalmente" (debemos dar algo de sentido a los textos traducidos)

![image](https://cloud.githubusercontent.com/assets/16881846/25810315/0da9399c-3410-11e7-9fc3-bc0386b4072c.png)

Otro ejemplo

![image](https://cloud.githubusercontent.com/assets/16881846/25810360/2a6145e8-3410-11e7-8776-1ded51a87dda.png)

Este también requiere un "arreglito"

![image](https://cloud.githubusercontent.com/assets/16881846/25810450/70e9cc9c-3410-11e7-8370-79a78677573a.png)

**Comment by julioosos** [comment]
Pensé que dejar quiz estaría bien pues todo el mundo lo entiende en lugar de cuestionario, en cuento al resto las arreglaré mañana

**Comment by profeIAP** [comment]
El "spanglish" no está bien visto en según que contextos... ya hablamos el miércoles de posibles "traducciones" 😉

**Comment by julioosos** [comment]
Errores de traducción corregidos tarea finiquitada.

**Comment by profeIAP** [comment]
Genial, gracias Julio.

Espero que tus cambios en quiz.js no hayan machacado los de @Mahc99 en la tarea #94 😏

**Comment by profeIAP** [comment]
Siento abrir la tarea pero acabo de detectar un mini fallo que agradecería resolvieses...

![image](https://cloud.githubusercontent.com/assets/16881846/25957165/f5b23a2c-366d-11e7-9e31-4a1e461ffa68.png)

**Comment by julioosos** [comment]
Terminada

**Comment by profeIAP** [comment]
Ha quedado genial, gracias Julio
