### ISSUE TITLE
Crear vista edición de PREGUNTA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#9]
Crear vista HTML que permita indicar el contenido de una pregunta y sus respuestas siguiendo el modelo definido en clase

![captura de pantalla de 2017-02-15 17-21-05](https://cloud.githubusercontent.com/assets/16881846/22983681/29282dde-f3a3-11e6-847c-ed4d393b2d74.png)

No es necesario que el formulario realice ninguna acción ni responda a ningún evento, sólo incluir los distintos elementos que aparecen en la imagen.

Se etiqueta como RETO por el tiempo que requerirá crear el formulario desde cero.

**Comment by profeIAP** [comment]
Te puede resultar de utilidad la siguiente [web para la creación de formularios para Bootstrap](http://bootsnipp.com/forms).

El ideal sería implementar una solución como la de los formularios de Google

![cuestionario](https://cloud.githubusercontent.com/assets/16881846/23562130/7cda68ac-0041-11e7-95be-dd42cde3e0d4.png)

pero, para nuestro nivel actual es prácticamente "ciencia ficción".

Yo me centraría en:

1. incluir los option buttons (el que permite elegir únicamente una respuesta)
1. poner cajas de texto a la derecha de cada uno de ellos para poder escribir las respuestas.

Aunque la herramienta que te he recomendado no permite poner dos columnas (una para los option buttons y otra para las cajas de texto) siempre puedes jugar con el _class="col-md-NNN"_ para organizar el contenido.

Sospecho que terminaremos hablando en clase: ve pidiendo "cita" ;)

**Comment by profeIAP** [comment]
Otra solución, aunque más fea e incómoda (ya lo arreglaremos más adelante) sería la siguiente

![captura de pantalla de 2017-03-03 18-59-29](https://cloud.githubusercontent.com/assets/16881846/23562649/a3e75016-0043-11e7-8c04-29b2faa05a3a.png)

**Comment by profeIAP** [comment]
Creo que he encontrado [la solución definitiva](http://www.smarttutorials.net/save-multiple-rows-of-invoice-data-in-mysql-database-using-php-jquery-and-bootstrap-3): usar una tabla (con cuatro filas fijas para cada una de las respuestas)

![captura de pantalla de 2017-03-03 20-43-05](https://cloud.githubusercontent.com/assets/16881846/23566469/48d90264-0052-11e7-8668-70eff2963768.png)

Considero que lo justo sería crear una nueva tarea para gestionar esta tabla en el formulario que estás creando ¿no os parece?

**Comment by profeIAP** [comment]
Genial Patri, ha quedado de lujo pero (ya sabes que si no lo pongo, "reviento" 😂) observo lo siguiente:
1. La columna respuesta correcta debería estar a la derecha (para que resulte más cómodo utilizar el fomrulario)
1. La etiqueta _Pregunta_ no debería estar centrada
1. Faltan los botones "Aceptar/Cancelar"
1. El ancho de la columna Correcta debería ser mucho más pequeño que el del texto de la respuesta ¿no te parece?

No obstante, sigo insistiendo en que está genial el formulario ¡Gracias!

**Comment by profeIAP** [comment]
Uuummm... ¿¡¿como "osas" cerrar la tarea sin subir los cambios al repositorio?!? 😏

**Comment by Patriexd** [comment]
sorry!! upps

**Comment by profeIAP** [comment]
Ocurre en las mejores familias, no te preocupes Patri

**Comment by Patriexd** [comment]
cierro la tarea

**Comment by profeIAP** [comment]
Sigue pendiente:
1. resolver [el problema del encabezado](https://github.com/profeIAP/retados/issues/9#issuecomment-287372937) 
1. el POST del formulario está apuntando a POST:/*alumnos*/guardar en lugar de al POST:/*preguntas*/guardar esperado

**Comment by Patriexd** [comment]
¡Quiero mi medallita por la tarea !🥇  xddd

**Comment by profeIAP** [comment]
Y estoy convencido que la tendrás peroooo... por qué no has dejado aquí ná
![captura de pantalla de 2017-03-24 20-03-11](https://cloud.githubusercontent.com/assets/16881846/24309695/23bcc476-10cd-11e7-91ec-888a971b13eb.jpg)

**Comment by Patriexd** [comment]
@profeIAP ¿Qué quieres que ponga?

**Comment by profeIAP** [comment]
Algo "con-sentido"

**Comment by profeIAP** [comment]
Dejarlo en blanco carece de sentido 😒

**Comment by profeIAP** [comment]
Uummm algo de "magia" 
si que tiene la preguntA 
¿pero te parece oportunA? 😏
