### ISSUE TITLE
Cargar BD con PREGUNTAS reales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#90]
Crear 5 o 6 PREGUNTAS que:
1. Tengan sentido (ya vale de "Pregunta 1" o similares)
1. Que traten algún tema conocido (descubrimiento de América, trigonometría, ...)
1. Que las RESPUESTAS no sean excesivamente difíciles de acertar

Deberás:
1. Eliminar las PREGUNTAS (y RESPUESTAS) actualmente existentes
1. Exportar el contenido a _model/script/datos_preguntas.sql_ y _model/script/datos_respuestas.sql_
1. Subir la BD con las preguntas cargadas a GitHub

**Comment by profeIAP** [comment]
Como hemos hablado en clase, guardaremos todos los datos en un único fichero model/script/datos_preguntas.sql

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Creo que has aplicado una _sustanciales_ rebajas:
1. Sólo se han creado 3 preguntas.
1. El análisis _sintático_ de la pregunta.ID=2 temo que no es correcto 😏

**Comment by profeIAP** [comment]
Cuando amplies/corrijas las PREGUNTAS y RESPUESTAS, recuerda:

1. Actualizar correctamente el contenido de la tabla ETIQUETAS 
1. Añadir el export de ETIQUETAS a _model/script/datos_preguntas.sql_ 

Gracias Carlos

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Sí que la has terminado pero creo que este curso no vas a aprobar Lengua Castellana 😏
