### ISSUE TITLE
Reorganizar el contenido de view/pregunta.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#91]
Reubicar el contenido del formulario de modo que:
1. El campo de ETIQUETAS y el texto de la PREGUNTA queden dentro del listado de RESPUESTAS
2. El conjunto completo quede con el mismo espacio a izquierda y derecha (centrado) respecto al título superior (el "jumbotron" en tonos grises)

![image](https://cloud.githubusercontent.com/assets/16881846/25756084/c2d88a68-31c5-11e7-8874-8d3b51c87a36.png)

**Comment by profeIAP** [comment]
Espectacular Fran... a la primera y "bien".
Sólo quedaría **implementar el apartado 2** que se exigía en la descripción de esta tarea.

**Comment by flobato322** [comment]
La cierro por fin!!

**Comment by profeIAP** [comment]
Con la ayuda del vecino... 
Di que sí, que te ha quedado muy bien.
Buen trabajo Fran pero, la próxima vez, acuérdate de preguntar (y enterarte) en lugar de "invertir" más tiempo del necesario en las cosas ;)
