### ISSUE TITLE
Implementar GET:/cuestionarios/practicar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#93]
Crear un **grupo** en index.php (similar al que tenemos para /login) al que denominarás /cuestionarios y en el que incluirás el método GET:/quiz renombrado como GET:/practicar.

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Casi, has debido liarte, observa cuál era el [contenido original del método GET:/quiz](https://github.com/profeIAP/retados/commit/bc7d6c0592bf011cd9f3e9bc5313579a9de9e126#diff-828e0013b8f3bc1bb22b4f57172b019dR131)

Has pedido renderizar un fichero (practicar.php) que no existe ¿Seguro que has probado el código antes de subirlo? 😏

**Comment by carlosaj98** [comment]
Terminada
