### ISSUE TITLE
Evitar que jQuiz muestre explicaciones

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#94]
Modificar js/quiz.js para que no aparezca el fragmento de texto explicando por qué una pregunta no es correcta.

![image](https://cloud.githubusercontent.com/assets/16881846/25813149/d1698e38-3418-11e7-8b45-3bb8fafd3002.png)

**Comment by Mahc99** [comment]
Terminada

**Comment by Mahc99** [comment]
No se que ha pasado, pero ya esta arreglado.

**Comment by profeIAP** [comment]
Genial, gracias Migue... observa la última referencia a esta tarea si estás interesado en averiguar qué ha pasado realmente 😬
