### ISSUE TITLE
Evitar que los 'quiz' peguen saltos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#95]
Modificar el comportamiento del módulo de los cuestionarios tipo test de modo que no pegue saltos al cambiar entre las distintas preguntas y/o al finalizar.

**Comment by profeIAP** [comment]
Aquí tienes el enlace para [bajar al pie de página](http://stackoverflow.com/questions/11715646/scroll-automatically-to-the-bottom-of-the-page)

**Comment by julioosos** [comment]
Me rindo

**Comment by profeIAP** [comment]
Nooooooooooooo... estó quedará anotado en los [anales](https://es.wikipedia.org/wiki/Anales) de la historia 😱

**Comment by profeIAP** [comment]
Subimos la "apuesta"... ¿alguien da "más"? 😏

**Comment by Rafaelcraftero** [comment]
compro

**Comment by profeIAP** [comment]
No te recomiendo comprarlo en tu situación actual... no digo que te tires por las preguntas fáciles (como otros) pero tampoco por las causas "perdidas" como esta.

Es su elección pero creo que queda poco tiempo para "experimentos" (se necesita "rendimiento")
