### ISSUE TITLE
Asegurar ON DELETE CASCADE entre las tablas USUARIO y PREGUNTAS

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/retados#98]
Asegurar que al borrar un USUARIO se eliminan automáticamente todas sus PREGUNTAS mediante la definición de la condicińo ON DELETE CASCADE en la relación "foreign key" de PREGUNTAS.ID_USUARIO -> USUARIO.ID

Sirva como referencia para implementarlo la tarea #6 

**NOTA:** se etiqueta como NORMAL al no ser la primera vez que lo implementamos en el proyecto.

**Comment by carlosaj98** [comment]
Terminada

**Comment by profeIAP** [comment]
Aunque se observa que has actualizado la SQL que crea la tabla PREGUNTAS (e incluye el ON DELETE CASCADE), la BD (a pesar de haber hecho un _checkout_ a los dos commits consecutivos que has hecho) no incluye el ON DELETE CASCADE

**Comment by carlosaj98** [comment]
Creo que ya

**Comment by profeIAP** [comment]
Desgraciadamente sigo sin ver los cambios, Carlos

**Comment by profeIAP** [comment]
Opto por asignarme la tarea tras hablar con Carlos y confirmar que no volverá (de momento) a clase.
Suerte Carlos, para lo que necesites, aquí nos tienes 👍
